src/objects/Account.object
<CustomObject>
</CustomObject>

unpackaged/config/trial/objects/Account.object
    <fields>
        <fullName>npo02__TotalOppAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Do not manually update. Updated by automatic processes. See excluded Record Types in Household Settings.</description>
        <label>Total Gifts</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

src/objects/Campaign.object
<CustomObject>
</CustomObject>

unpackaged/config/trial_tso/objects/Campaign.object
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Use this Record Type for Events</description>
        <label>Event</label>
    </recordTypes>

src/objects/Contact.object
<CustomObject>
</CustomObject>

unpackaged/config/trial/objects/Contact.object
    <fields>
        <fullName>npo02__Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household</label>
        <referenceTo>npo02__Household__c</referenceTo>
        <relationshipLabel>Household Members</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>

unpackaged/config/trial/objects/Contact.object
    <fields>
        <fullName>npo02__TotalOppAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>See Household Settings for excluded Record Types.  Do not update, updated by automatic process.</description>
        <label>Total Gifts</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

src/objects/npo02__Household__c.object
<CustomObject>
    <label>Household</label>
    <pluralLabel>Households</pluralLabel>
    <nameField>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
</CustomObject>

unpackaged/config/trial/objects/npo02__Household__c.object
    <fields>
        <fullName>npo02__TotalOppAmount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>See Household Settings for excluded Record Types and FY/CY.  Do not update, updated by automatic process.</description>
        <label>Total Gifts</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

src/objects/npo02__Households_Settings__c.object
<CustomObject>
</CustomObject>

unpackaged/config/trial/objects/npo02__Households_Settings__c.object
    <fields>
        <fullName>npo02__Always_Rollup_to_Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When selected, Salesforce will ALWAYS roll up donor data to the Opportunity&apos;s Primary Contact, and corresponding Household Account or record, even if the Opportunity is not from an individual. If left unselected, only the organization will receive credit.</description>
        <inlineHelpText>Always rollup donor statistics to the primary Contact Role, and corresponding household, on an opportunity, even if the opportunity is not from an individual (i.e. from a company, foundation, etc.)</inlineHelpText>
        <label>Always Rollup to Primary Contact Role</label>
        <type>Checkbox</type>
    </fields>

unpackaged/config/trial/objects/npo02__Households_Settings__c.object
    <fields>
        <fullName>npo02__Enable_Opp_Rollup_Triggers__c</fullName>
        <defaultValue>true</defaultValue>
        <description>DEPRECATED. Trigger behavior now controlled in the Trigger Configuration page of NPSP Settings.</description>
        <inlineHelpText>DEPRECATED. Trigger behavior now controlled in the Trigger Configuration page of NPSP Settings.</inlineHelpText>
        <label>DEPRECATED-Enable_Opp_Rollup_Triggers</label>
        <type>Checkbox</type>
    </fields>

unpackaged/config/trial/objects/npo02__Households_Settings__c.object
    <fields>
        <fullName>npo02__Excluded_Account_Opp_Rectypes__c</fullName>
        <description>Names of Opportunity Record Types to exclude from statistics when rolling up Account Opportunities.</description>
        <inlineHelpText>Names of Opportunity Record Types to exclude from statistics when rolling up Account Opportunities.</inlineHelpText>
        <label>Opp RecTypes Excluded for Account Rollup</label>
        <length>255</length>
        <type>Text</type>
    </fields>

unpackaged/config/trial/objects/npo02__Households_Settings__c.object
    <fields>
        <fullName>npo02__Excluded_Account_Opp_Types__c</fullName>
        <description>Opportunities that have this value in the Type picklist won&apos;t be included in rollups to the Account.</description>
        <inlineHelpText>Values for the Opportunity Type field to exclude from statistics when rolling up Account Opportunities.</inlineHelpText>
        <label>Opp Types Excluded for Account Rollup</label>
        <length>255</length>
        <type>Text</type>
    </fields>

unpackaged/config/trial/objects/npo02__Households_Settings__c.object
    <fields>
        <fullName>npo02__Excluded_Contact_Opp_Rectypes__c</fullName>
        <description>Opportunities with the selected record types won&apos;t be included in rollups to the Contact. Control or Command click to select more than one record type.</description>
        <inlineHelpText>Names of Opportunity Record Types to exclude from statistics when rolling up Contact Opportunities.</inlineHelpText>
        <label>Opp RecTypes Excluded for Contact Rollup</label>
        <length>255</length>
        <type>Text</type>
    </fields>

unpackaged/config/trial/objects/npo02__Households_Settings__c.object
    <fields>
        <fullName>npo02__Excluded_Contact_Opp_Types__c</fullName>
        <description>Opportunities that have this value in the Type picklist won&apos;t be included in rollups to the Contact.</description>
        <inlineHelpText>Values for the Opportunity Type field to exclude from statistics when rolling up Contact Opportunities.</inlineHelpText>
        <label>Opp Types Excluded for Contact Rollup</label>
        <length>255</length>
        <type>Text</type>
    </fields>

unpackaged/config/trial/objects/npo02__Households_Settings__c.object
    <fields>
        <fullName>npo02__Household_Mailing_List_ID__c</fullName>
        <description>The report ID of the Household Mailing List Report used for Household-deduplicated Campaign mailing lists.  Report should be of Campaigns with Contacts, where Member Status does not contain &apos;Duplicate&apos;</description>
        <inlineHelpText>The report ID of the Household Mailing List Report used for Household-deduplicated Campaign mailing lists.  Report should be of Campaigns with Contacts, where Member Status does not contain &apos;Duplicate&apos;</inlineHelpText>
        <label>Household Mailing List Report</label>
        <length>18</length>
        <type>Text</type>
    </fields>

unpackaged/config/trial/objects/npo02__Households_Settings__c.object
    <fields>
        <fullName>npo02__Household_Rules__c</fullName>
        <description>Specifies which Contacts will have Households objects automatically created for them.  Note that this is only used for Contacts using the One-to-One or Individual Account Model.  This is ignored for Contacts with the Household Account Model.</description>
        <inlineHelpText>Specifies which Contacts will have Households objects automatically created for them.  Note that this is only used for Contacts using the One-to-One or Individual Account Model.  This is ignored for Contacts with the Household Account Model.</inlineHelpText>
        <label>Household Object Rules</label>
        <length>255</length>
        <type>Text</type>
    </fields>

unpackaged/config/trial/objects/npo02__Households_Settings__c.object
    <fields>
        <fullName>npo02__Membership_Record_Types__c</fullName>
        <defaultValue>&quot;Membership&quot;</defaultValue>
        <description>Names of Opportunity Record Types, such as Membership, that you want to roll up separately from other Opportunity Record Types.</description>
        <inlineHelpText>Names of Opportunity Record Types, such as Membership, that you want to roll up separately from other Opportunity Record Types.</inlineHelpText>
        <label>Membership Record Type Names</label>
        <length>255</length>
        <type>Text</type>
    </fields>

unpackaged/config/trial/objects/npo02__Households_Settings__c.object
    <fields>
        <fullName>npo02__Rollup_N_Day_Value__c</fullName>
        <defaultValue>365</defaultValue>
        <description>Provide a value for &apos;N day&apos; rollups, where &apos;N&apos; is the number of days from today into the past.  This value defaults to rollup over the past 365 days.</description>
        <inlineHelpText>Provide a value for &apos;N day&apos; rollups, where &apos;N&apos; is the number of days from today into the past.  This value defaults to rollup over the past 365 days.</inlineHelpText>
        <label>Rollup N Day Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

unpackaged/config/trial/objects/npo02__Households_Settings__c.object
    <fields>
        <fullName>npo02__Use_Fiscal_Year_for_Rollups__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checking this box will cause Opportunity rollup totals to respect fiscal year, instead of calendar years settings. To set Fiscal Year information, go to Setup-&gt;Company Profile-&gt;Fiscal Year.  NOTE: Custom Fiscal Year Settings are NOT supported.</description>
        <inlineHelpText>Checking this box will cause Opportunity rollup totals to respect fiscal year, instead of calendar years settings. To set Fiscal Year information, go to Setup-&gt;Company Profile-&gt;Fiscal Year.  NOTE: Custom Fiscal Year Settings are NOT supported.</inlineHelpText>
        <label>Use Fiscal Year for Rollups</label>
        <type>Checkbox</type>
    </fields>

src/classes/HH_CampaignDedupeBTN_TEST.cls
/*
    Copyright (c) 2011, Salesforce.org
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Salesforce.org
* @date 2011 (2.3)
* @group Households
* @description test class for the campaign dedupe button from the campaign record 
*/
@isTest
private class HH_CampaignDedupeBTN_TEST {  
  
 
    /*******************************************************************************************************
    * @description test the Campaign Dedupe controller 
    * @return void
    ********************************************************************************************************/
    private static testMethod void testCampaignHHReport(){
      npo02__Households_Settings__c householdSettingsForTests = UTIL_CustomSettingsFacade.getHouseholdsSettingsForTests(
                new npo02__Households_Settings__c (
                    npo02__Household_Rules__c = HH_Households.ALL_PROCESSOR, 
                    npo02__Always_Rollup_to_Primary_Contact__c = false,
                    npo02__Enable_Opp_Rollup_Triggers__c = true,
                    npo02__Excluded_Account_Opp_Rectypes__c = null,
                    npo02__Excluded_Account_Opp_Types__c = null,
                    npo02__Excluded_Contact_Opp_Rectypes__c = null,
                    npo02__Excluded_Contact_Opp_Types__c = null,
                    npo02__Membership_Record_Types__c = null,                     
                    npo02__Use_Fiscal_Year_for_Rollups__c = true, 
                    npo02__Rollup_N_Day_Value__c = 10,
                    npo02__Household_Mailing_List_ID__c = '0000000'                    
                ));
            
    // create test data
    Account acct = new Account (
      Name='Test Account'
    );
    insert acct;
    
    Contact con = new Contact (
      FirstName='Kevin',
      LastName='Test',
      AccountId = acct.id,    
      npo02__TotalOppAmount__c = 100
    );
    insert con;
    id hhid = [select npo02__Household__r.id from Contact where id = :con.id].npo02__household__r.id;
    system.assert(hhid != null);
    UTIL_Debug.debug('HHID IS===================' + hhid);
    Contact con2 = new Contact (
      FirstName = 'Amy',
      LastName = 'Test',
      AccountId = acct.id,            
      npo02__household__c = hhid
    );
    UTIL_Debug.debug('HHID IS NOW===================' + hhid);
    
    system.assert(con2.npo02__household__c != null);
    insert con2;
    
    Campaign camp = new Campaign (
      Name = 'MyCampaign',
      Status = 'Planned',
      isActive = true
    );
    insert camp;
    
    CampaignMember campm1 = new CampaignMember(
      CampaignID = camp.id,
      ContactID = con.id,
      Status = 'Sent'      
    );
    insert campm1;
    
    CampaignMember campm2 = new CampaignMember(
      CampaignID = camp.id,
      ContactID = con2.id,
      Status = 'Sent'       
    );
    insert campm2;
        
    //now run our report
    Test.startTest();
    ApexPages.StandardController sc = new ApexPages.StandardController(camp);
    HH_CampaignDedupeBTN_CTRL deduper = new HH_CampaignDedupeBTN_CTRL(sc);
    PageReference pr = deduper.runReport();
    Test.stopTest();
    
    String campm1Status = [select Status from CampaignMember where id = :campm1.id].Status;
    String campm2Status = [select Status from CampaignMember where id = :campm2.id].Status;
    
    system.assertEquals('Sent', campm1Status);
    //We cannot test for "Sent -  Household duplicate", which should be the actual status that
    //this campaign member gets, because that status is not visible without seealldata=true
    system.assertEquals('Responded', campm2Status);  
  
  }
}