src/objects/Address__c.object
<CustomObject>
    <description>Custom object for storing additional addresses for Household Accounts in the Nonprofit Success Pack.</description>
    <fields>
        <fullName>Ambiguous__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether more than one valid Address was found when attempting to validate it through an external service.</description>
        <inlineHelpText>Indicates whether more than one valid Address was found when attempting to validate it through an external service.</inlineHelpText>
        <label>Ambiguous</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Household_Account__c</fullName>
        <description>Lookup to the Account associated with this Address.</description>
        <inlineHelpText>Lookup to the Account associated with this Address.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>MailingCity__c</fullName>
        <label>Mailing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingPostalCode__c</fullName>
        <label>Mailing Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingState__c</fullName>
        <label>Mailing State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MailingStreet__c</fullName>
        <label>Mailing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the Address has been verified by an external address verification service.</description>
        <inlineHelpText>Indicates whether the Address has been verified by an external address verification service.</inlineHelpText>
        <label>Verified</label>
        <type>Checkbox</type>
    </fields>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Address_Authentication_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Credentials for the SmartyStreets address verification/normalization integration.</description>
    <fields>
        <fullName>Auth_ID__c</fullName>
        <inlineHelpText>LiveAddress API Auth ID - get yours at https://smartystreets.com/account/keys</inlineHelpText>
        <label>Auth ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auth_Token__c</fullName>
        <inlineHelpText>LiveAddress API Auth Token (unencoded) - get yours at https://smartystreets.com/account/keys</inlineHelpText>
        <label>Auth Token</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HTML_Key__c</fullName>
        <inlineHelpText>LiveAddress API numeric HTML Auth Key (depends on matching domain) - get yours at https://smartystreets.com/account/keys</inlineHelpText>
        <label>HTML Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Address Authentication Settings</label>
</CustomObject>

src/objects/Address_Verification_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings for automatic address verification and normalization.</description>
    <fields>
        <fullName>Auth_ID__c</fullName>
        <description>Address verification  ID/Username - For the SmartyStreets API get yours at https://smartystreets.com/account/keys</description>
        <inlineHelpText>Address verification  ID/Username - For the SmartyStreets API get yours at https://smartystreets.com/account/keys</inlineHelpText>
        <label>Auth ID</label>
        <length>124</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auth_Token__c</fullName>
        <description>Authentication Token/Password - For the SmartyStreets API get yours at https://smartystreets.com/account/keys</description>
        <inlineHelpText>Authentication Token/Password - For the SmartyStreets API get yours at https://smartystreets.com/account/keys</inlineHelpText>
        <label>Auth Token</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Auto_Update_Addresses__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, changed addresses get updated automatically with the response from the service (when there is one verified result).</inlineHelpText>
        <label>Auto-Update Addresses</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Clear_Invalid_Addresses__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, any US account address that the service marks undeliverable will automatically get cleared out. (You can review the invalid entry in the Address record.)</inlineHelpText>
        <label>Clear Invalid Addresses</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Automatic_Verification__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, automatic address verification is enabled via Apex triggers.</inlineHelpText>
        <label>Enable Automatic Verification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reject_Ambiguous_Addresses__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>If checked, address verification will mark ambiguous addresses as invalid; if unchecked, it will accept the first suggestion as the valid address.</inlineHelpText>
        <label>Reject Ambiguous Addresses</label>
        <type>Checkbox</type>
    </fields>
    <label>Address Verification Settings</label>
</CustomObject>

src/objects/npe01__Contacts_And_Orgs_Settings__c.object
<CustomObject>
</CustomObject>

src/classes/ADDR_Validator_TEST.cls
@isTest
public with sharing class ADDR_Validator_TEST {

    // if you only want to run one test in this class, fill in its name here.
    // if you want to run all tests, then use '*'
    private static string strTestOnly = '*';
    
    public static void createDefaultSettings() {
        // use the household account model
        CAO_Constants.getContactsSettingsForTests(
            new npe01__Contacts_and_Orgs_Settings__c (npe01__Account_Processor__c = CAO_Constants.HH_ACCOUNT_PROCESSOR));

        // create the basic api authentication settings
        Address_Authentication_Settings__c authSettings = Address_Authentication_Settings__c.getOrgDefaults();
        authSettings.Auth_ID__c = 'hey';
        authSettings.Auth_Token__c = 'there';
        insert authSettings;

        // set the verification settings
        Address_Verification_Settings__c settings = Address_Verification_Settings__c.getOrgDefaults();
        settings.Auto_Update_Addresses__c = true;
        settings.Clear_Invalid_Addresses__c = true;
        settings.Enable_Automatic_Verification__c = true;
        settings.Reject_Ambiguous_Addresses__c = true;
        insert settings;
    }
    
    static testMethod void testContactAddress() {
    	if (strTestOnly != '*' && strTestOnly != 'testContactAddress') return;
    	
        createDefaultSettings();
        Test.setMock(HttpCalloutMock.class, new ADDR_MockHttpRespGenerator_TEST());
              
        Contact contact = new contact(firstname='Test', lastname='Person'); 
        insert contact;
        
        //check household got created for contact
        contact = [select Account.Id from Contact where Id = :contact.Id];
        Id accountId = contact.Account.Id;
        System.assertNotEquals(null, accountId);
         
        // update contact with address to get the Address__c record created
        contact.MailingStreet = 'single-address-response';
        contact.MailingCity = 'Cupertino';
        contact.MailingState = 'CA';
        contact.MailingPostalCode = '95014';
        Test.StartTest();
        update contact;
        Test.StopTest();
        
        Address__c[] av = [select MailingStreet__c, MailingState__c, MailingPostalCode__c, Verified__c 
                from Address__c where Household_Account__c = :accountId];
        System.assertEquals(1, av.size());
        System.assertEquals('1 Infinite Loop', av[0].MailingStreet__c);
        System.assertEquals('CA', av[0].MailingState__c);
        System.assertEquals('95014-2083', av[0].MailingPostalCode__c);
        System.assertEquals(true, av[0].Verified__c);
    }

    static testMethod void testContactBadAddress() {
    	if (strTestOnly != '*' && strTestOnly != 'testContactBadAddress') return;
    	
        createDefaultSettings();
        Test.setMock(HttpCalloutMock.class, new ADDR_MockHttpRespGenerator_TEST());
              
        Contact contact = new contact(firstname='Test', lastname='Person'); 
        insert contact;
        
        //check household got created for contact
        contact = [select Account.Id from Contact where Id = :contact.Id];
        Id accountId = contact.Account.Id;
        System.assertNotEquals(null, accountId);
         
        // update contact with address to get the Address__c record created
        contact.MailingStreet = 'bogus-address-for-test';
        contact.MailingCity = 'chicago';
        contact.MailingState = 'il';
        contact.MailingPostalCode = '60606';
        Test.StartTest();
        update contact;
        Test.StopTest();

        Address__c[] av = [select Verified__c from Address__c where Household_Account__c = :contact.AccountId];       
        System.assertEquals(1, av.size());
        System.assertEquals(false, av[0].Verified__c);
    }
    
    static testMethod void testContactAmbiguousAddress() {
        if (strTestOnly != '*' && strTestOnly != 'testContactAmbiguousAddress') return;
        
        createDefaultSettings();
        Test.setMock(HttpCalloutMock.class, new ADDR_MockHttpRespGenerator_TEST());
              
        Contact contact = new contact(firstname='Test', lastname='Person'); 
        insert contact;
        
        //check household got created for contact
        contact = [select Account.Id from Contact where Id = :contact.Id];
        Id accountId = contact.Account.Id;
        System.assertNotEquals(null, accountId);
         
        // update contact with address to get the Address__c record created
        contact.MailingStreet = 'ambiguous-address-for-test';
        contact.MailingCity = 'chicago';
        contact.MailingState = 'il';
        contact.MailingPostalCode = '60606';
        Test.StartTest();
        update contact;
        Test.StopTest();

        Address__c[] av = [select Verified__c, Ambiguous__c from Address__c 
                            where Household_Account__c = :accountId];       
        System.assertEquals(1, av.size());
        System.assertEquals(false, av[0].Verified__c);
        System.assertEquals(true, av[0].Ambiguous__c);
    }

    static testMethod void testContactZipOnly() {
    	if (strTestOnly != '*' && strTestOnly != 'testContactZipOnly') return;
    	
    	createDefaultSettings();
        Test.setMock(HttpCalloutMock.class, new ADDR_MockHttpRespGenerator_TEST());
        
        Contact contact = new contact(firstname='Test', lastname='Person'); 
        insert contact;
        
        //check household got created for contact
        contact = [select Account.Id from Contact where Id = :contact.Id];
        Id accountId = contact.Account.Id;
        System.assertNotEquals(null, accountId);
         
        // update contact with postal code to get the Address__c record created
        contact.MailingPostalCode = '60606';
        Test.StartTest();
        update contact;
        Test.StopTest();
                        
        Address__c[] av = [select MailingCity__c, MailingPostalCode__c, Verified__c 
                            from Address__c where Household_Account__c = :accountId];      
        System.assertEquals('98236', av[0].MailingPostalCode__c);
        System.assertEquals('Clinton', av[0].MailingCity__c);
        /*
        contact[] c1 = [select id, MailingStreet, MailingCity from contact where id = :contact.id];
        System.assertEquals(null, c1[0].MailingStreet);
        System.assertEquals('98236', c1[0].MailingPostalCode__c);
        System.assertEquals('Clinton', c1[0].MailingCity);*/
    }

    static testMethod void testContactCityAndStateOnly() {
    	if (strTestOnly != '*' && strTestOnly != 'testContactCityAndStateOnly') return;
    	
        createDefaultSettings();
        Test.setMock(HttpCalloutMock.class, new ADDR_MockHttpRespGenerator_TEST());
        
        Contact contact = new contact(firstname='Test', lastname='Person'); 
        insert contact;
        
        //check household got created for contact
        contact = [select Account.Id from Contact where Id = :contact.Id];
        Id accountId = contact.Account.Id;
        System.assertNotEquals(null, accountId);
         
        // update contact with to get the Address__c record created
        contact.MailingCity = 'Clinton';
        contact.MailingState = 'WA';
        Test.StartTest();
        update contact;
        Test.StopTest();

        Address__c[] av = [select id, MailingCity__c, MailingPostalCode__c from Address__c 
                            where Household_Account__c = :contact.AccountId];        
        System.assertEquals('98236', av[0].MailingPostalCode__c);
        System.assertEquals('Clinton', av[0].MailingCity__c);
        /*
        contact[] c1 = [select id, MailingStreet, MailingPostalCode from contact where id = :contact.id];
        System.assertEquals(null, c1[0].MailingStreet)
        System.assertEquals('Clinton', c1[0].MailingCity__c);
        System.assertEquals('98236', c1[0].MailingPostalCode);*/
    }

    static testMethod void testBatch() {
    	if (strTestOnly != '*' && strTestOnly != 'testBatch') return;
    	
        createDefaultSettings();
        Test.setMock(HttpCalloutMock.class, new ADDR_MockHttpRespGenerator_TEST());
        
        Test.StartTest();
        ADDR_Validator_Batch.verifyAllAddresses();
        Test.StopTest();
    }

    static testMethod void testController() {
    	if (strTestOnly != '*' && strTestOnly != 'testController') return;
    	
        STG_PanelADDRVerification_CTRL sc = new STG_PanelADDRVerification_CTRL();
        
        sc.apiSettings.HTML_Key__c = 'skldjflsdkfj';
        sc.saveApiSettings();
        System.assertEquals('Saved.', sc.apiSettingsSaveMessage);

        sc.saveVerificationSettings();

        sc.apiTestEntry = '98236';
        sc.testApi();
        system.assertNotEquals(null, sc.apiTestResult);

        Test.startTest();
        sc.bulkVerify();
        Test.stopTest();
    }
}