src/objects/Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <description>The amount of the Opportunity allocated to this General Accounting Unit. Leave blank for percent-based Allocations.</description>
        <inlineHelpText>The amount of the Opportunity allocated to this General Accounting Unit. Leave blank for percent-based Allocations.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Campaign associated with this Allocation. Use this field if you want new Opportunities associated with this Campaign to be allocated in the same way.</description>
        <inlineHelpText>The Campaign associated with this Allocation. Use this field if you want new Opportunities associated with this Campaign to be allocated in the same way.</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>GAU Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>General_Accounting_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The General Accounting Unit this Allocation is attributed to. Only General Accounting Units marked as active are available for new Allocations.</description>
        <inlineHelpText>The General Accounting Unit this Allocation is attributed to. Only General Accounting Units marked as active are available for new Allocations.</inlineHelpText>
        <label>General Accounting Unit</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <errorMessage>Choose an active General Accounting Unit for this Allocation. You cannot modify an Allocation assigned to an inactive General Accounting Unit.</errorMessage>
            <filterItems>
                <field>General_Accounting_Unit__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Payment__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.Payment__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>You must select an active General Accounting Unit for this Allocation.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>General_Accounting_Unit__c</referenceTo>
        <relationshipLabel>GAU Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity you want this Allocation attributed to. NPSP rolls up all Opportunities in a Closed/Won stage to this Allocation's General Accounting Unit.</description>
        <inlineHelpText>The Opportunity you want this Allocation attributed to. NPSP rolls up all Opportunities in a Closed/Won stage to this Allocation's General Accounting Unit.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>GAU Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Percent__c</fullName>
        <description>Percent of Opportunity amount allocated to this Allocation's General Accounting Unit. If you later modify the Opportunity amount, NPSP will update the allocation amount on the General Accounting Unit.</description>
        <inlineHelpText>Percent of Opportunity amount allocated to this Allocation's General Accounting Unit. If you later modify the Opportunity amount, NPSP will update the allocation amount on the General Accounting Unit.</inlineHelpText>
        <label>Percent</label>
        <precision>9</precision>
        <scale>6</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Recurring_Donation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Recurring Donation this Allocation is attributed to. NPSP automatically allocates all new Opportunities associated with the Recurring Donation in the same way.</description>
        <inlineHelpText>The Recurring Donation this Allocation is attributed to. NPSP automatically allocates all new Opportunities associated with the Recurring Donation in the same way.</inlineHelpText>
        <label>Recurring Donation</label>
        <referenceTo>npe03__Recurring_Donation__c</referenceTo>
        <relationshipLabel>GAU Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GAU Allocation</label>
    <nameField>
        <displayFormat>ALL-{0}</displayFormat>
        <label>GAU Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GAU Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Allocations_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings for the allocation of Opportunities into General Accounting Units.</description>
    <label>Allocations Settings</label>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
</CustomObject>

unpackaged/config/trial_tso/objects/Campaign.object
    <recordTypes>
        <fullName>Event</fullName>
        <active>true</active>
        <description>Use this Record Type for Events</description>
        <label>Event</label>
    </recordTypes>

unpackaged/config/trial_tso/objects/Campaign.object
    <recordTypes>
        <fullName>General</fullName>
        <active>true</active>
        <description>Use this Record Type to create lists of people</description>
        <label>General</label>
    </recordTypes>

src/objects/General_Accounting_Unit__c.object
<CustomObject>
    <description>Accounting units used for allocating Opportunities.</description>
    <label>General Accounting Unit</label>
    <nameField>
        <label>General Accounting Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Accounting Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/npe03__Recurring_Donation__c.object
<CustomObject>
</CustomObject>

unpackaged/config/trial/objects/npe03__Recurring_Donation__c.object
    <fields>
        <fullName>npe03__Amount__c</fullName>
        <description>The amount for each installment Opportunity.</description>
        <inlineHelpText>The amount for each installment Opportunity.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

unpackaged/config/trial/objects/npe03__Recurring_Donation__c.object
    <fields>
        <fullName>npe03__Date_Established__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The initial inception date for this Recurring Donation. The default is the current date.</description>
        <inlineHelpText>The initial inception date for this recurring donation. The default is the current date.</inlineHelpText>
        <label>Date Established</label>
        <type>Date</type>
    </fields>

unpackaged/config/trial/objects/npe03__Recurring_Donation__c.object
    <fields>
        <fullName>npe03__Installment_Period__c</fullName>
        <description>How often you’ll receive the donations. NOTE: Changing the installment period for an existing Fixed-Length Recurring Donation may result in the loss and re-creation of open opportunities. Any data associated with those opportunities may be lost.</description>
        <inlineHelpText>The Installment Period along with Installment Frequency defines the installment schedule of this Recurring Donation. For example, if Installment Period is Monthly and Installment Frequency is 3, the schedule is defined as &quot;every 3 months&quot;.</inlineHelpText>
        <label>Installment Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                    <default>true</default>
                    <label>Monthly</label>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>1st and 15th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

unpackaged/config/trial/objects/npe03__Recurring_Donation__c.object
    <fields>
        <fullName>npe03__Open_Ended_Status__c</fullName>
        <label>Open Ended Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

unpackaged/config/trial/objects/npe03__Recurring_Donation__c.object
    <fields>
        <fullName>npe03__Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Recurring Donations</relationshipLabel>
        <relationshipName>RecurringDonations</relationshipName>
        <type>Lookup</type>
    </fields>

unpackaged/config/trial/objects/npe03__Recurring_Donation__c.object
    <fields>
        <fullName>npe03__Schedule_Type__c</fullName>
        <description>Tells Salesforce how to compute the amount for each child opportunity, based on what you&apos;ve entered in the Amount field. For Fixed-Length Recurring Donations only.</description>
        <inlineHelpText>Whether the Amount is used for each installment (Multiple By), or Amount is split between installments (Divide By).  Only used with Non-Open Ended Recurring Donations.</inlineHelpText>
        <label>Schedule Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Multiply By</fullName>
                </value>
                <value>
                    <fullName>Divide By</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Opportunity.object
<CustomObject>
</CustomObject>

unpackaged/config/trial_tso/objects/Opportunity.object
    <recordTypes>
        <fullName>Donation</fullName>
        <active>true</active>
        <businessProcess>Donation</businessProcess>
        <description>Donation Received</description>
        <label>Donation</label>
    </recordTypes>

src/classes/ALLO_ManageAllocations_TEST.cls
/*
    Copyright (c) 2014, Salesforce.org
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Salesforce.org
* @date 2014
* @group Allocations
* @group-content ../../ApexDocContent/Allocations.htm
* @description Tests for the Manage Allocations page. 
*/
@isTest
private class ALLO_ManageAllocations_TEST {

    /*********************************************************************************************************
    * @description If you only want to run a single test in this class, fill in its name here.
    * If you want to run all tests, then use '*'
    */
    private static string strTestOnly = '*';

    /*******************************************************************************************************
    * @description Setup of allocations settings.
    * @param alloset An instance of Allocations_Settings__c custom setting. Calling this method with a null
    * parameter uses default settings.
    * @return void Modifies settings, returns nothing.
    ********************************************************************************************************/
    private static void setupSettings (Allocations_Settings__c alloset) {
        //set running user to avoid dml issue            
        System.runAs(new User(id = UserInfo.getUserId())){
            if (alloset!=null)
                UTIL_CustomSettingsFacade.getAllocationsSettingsForTests(alloset);
            else 
                UTIL_CustomSettingsFacade.getAllocationsSettingsForTests(new Allocations_Settings__c());

        }
    }

    /*******************************************************************************************************
    * @description Runs manage allocations page on an opportunity with no allocations. Adds then deletes a
    * row, then inserts an allocation and verifies the allocation was created properly.
    ********************************************************************************************************/
    static testMethod void testOpp() {
        if (strTestOnly != '*' && strTestOnly != 'testOpp') return;
        setupSettings(null);
        
        Account acc = new Account(Name='foo');
        insert acc;
        Opportunity opp = new Opportunity(Name='foo', Amount = 8, AccountID=acc.id, CloseDate=system.today(), StageName=UTIL_UnitTestData_TEST.getClosedWonStage());
        insert opp;
        General_Accounting_Unit__c gau = new General_Accounting_Unit__c(Name='foo');
        insert gau;

        PageReference pageRef = Page.ALLO_ManageAllocations;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', opp.id);
        ALLO_ManageAllocations_CTRL ctrl = new ALLO_ManageAllocations_CTRL(
            new ApexPages.StandardSetController(new List<Allocation__c>())
        );

        system.assertEquals(1,ctrl.listAllo.size(),'The list of allocations should have a single empty allocation.');
        system.assertEquals(null,ctrl.listAllo[0].id,'The allocation should have no Id.');
        system.assertEquals(opp.Id,ctrl.listAllo[0].Opportunity__c,'The allocation should be attributed to current opportunity.');

        ctrl.rowNumber = 0;
        ctrl.addRow();
        system.assertEquals(2,ctrl.listAllo.size(),'Adding a row increases the size of the allocation list.');

        ctrl.listAllo[0].Percent__c = 50;
        ctrl.listAllo[0].General_Accounting_Unit__c = gau.id;
        ctrl.rowNumber = 1;
        ctrl.delRow();
        Test.startTest();
        ctrl.saveClose();
        Test.stopTest();

        list<Allocation__c> queryAllo = [SELECT Id, Percent__c, Amount__c FROM Allocation__c WHERE Opportunity__c=:opp.id];
        system.assertEquals(1,queryAllo.size(),'The single allocation should be saved.');
        system.assertEquals(4,queryAllo[0].Amount__c,'The amount should be calculated based on the percent.');
    }

    /*******************************************************************************************************
    * @description Runs manage allocations page on a campaign with two allocations. Adds a new allocation,
    * deletes an existing one, and verifies the results.
    ********************************************************************************************************/
    @isTest static void testCam() {
        if (strTestOnly != '*' && strTestOnly != 'testCam') return;
        setupSettings(null);
        
        Account acc = new Account(Name='foo');
        insert acc;
        General_Accounting_Unit__c campaigngau = new General_Accounting_Unit__c(Name='foo');
        insert campaigngau;
        Campaign cam = new Campaign(Name='Foo', IsActive=true);
        insert cam;

        list<Allocation__c> alloForInsert = new list<Allocation__c>();
        Allocation__c percentAllo = new Allocation__c(Campaign__c=cam.id, Percent__c = 50, General_Accounting_Unit__c = campaigngau.id);
        alloForInsert.add(percentAllo);
        Allocation__c amountAllo = new Allocation__c(Campaign__c=cam.id, Amount__c = 4, General_Accounting_Unit__c = campaigngau.id);
        alloForInsert.add(amountAllo);
        insert alloForInsert;

        PageReference pageRef = Page.ALLO_ManageAllocations;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', cam.id);
        ALLO_ManageAllocations_CTRL ctrl = new ALLO_ManageAllocations_CTRL(
            new ApexPages.StandardSetController(new List<Allocation__c>())
        );

        system.assertEquals(2,ctrl.listAllo.size(),'The list of allocations should have two current campaign allocations.');

        ctrl.addRow();
        system.assertEquals(3,ctrl.listAllo.size(),'Adding a row increases the size of the allocation list.');

        //delete the first allocation on the list
        ctrl.rowNumber = 0;
        ctrl.delRow();

        ctrl.listAllo[1].Amount__c = 5;
        ctrl.listAllo[1].General_Accounting_Unit__c = campaigngau.id;
        Test.startTest();
        ctrl.saveClose();
        Test.stopTest();

        list<Allocation__c> queryAllo = [SELECT Id, Percent__c, Amount__c FROM Allocation__c WHERE Campaign__c=:cam.id];
        system.assertEquals(2,queryAllo.size(),'2 allocations should be saved, one original allocation should be deleted.');
    }

    /*******************************************************************************************************
    * @description Runs manage allocations page on a recurring with two allocations. Adds a new allocation,
    * deletes an existing one, and verifies the results.
    ********************************************************************************************************/
    @isTest static void testRD() {
        if (strTestOnly != '*' && strTestOnly != 'testRD') return;
        setupSettings(null);
        
        Account acc = new Account(Name='foo');
        insert acc;
        General_Accounting_Unit__c gau = new General_Accounting_Unit__c(Name = 'foo');
        insert gau;
        npe03__Recurring_Donation__c rd = new npe03__Recurring_Donation__c(
            Name = 'foo', 
            npe03__Installment_Period__c = system.label.npe03.RecurringDonationInstallmentPeriodYearly, 
            npe03__Date_Established__c=date.newinstance(1984,01,29), 
            npe03__Organization__c = acc.id, 
            npe03__Amount__c = 20,
            npe03__Schedule_Type__c = system.label.npe03.RecurringDonationMultiplyValue,
            npe03__Open_Ended_Status__c = system.label.npe03.RecurringDonationOpenStatus
        );
        insert rd;
        list<Allocation__c> alloForInsert = new list<Allocation__c>();
        Allocation__c percentAllo = new Allocation__c(Recurring_Donation__c = rd.id, Percent__c = 50, General_Accounting_Unit__c = gau.id);
        alloForInsert.add(percentAllo);
        Allocation__c amountAllo = new Allocation__c(Recurring_Donation__c = rd.id, Amount__c = 10, General_Accounting_Unit__c = gau.id);
        alloForInsert.add(amountAllo);
        insert alloForInsert;

        Integer oppCnt = [SELECT Count() FROM Opportunity WHERE npe03__Recurring_Donation__c = :rd.Id];
        system.assertNotEquals(0, oppCnt, 'There should be at least one installment Opportunity');
        system.assertEquals(oppCnt * 2, [SELECT Count() FROM Allocation__c WHERE Opportunity__r.npe03__Recurring_Donation__c = :rd.Id],
            'There should be two Allocations per Installment Opportunity');

        PageReference pageRef = Page.ALLO_ManageAllocations;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', rd.id);
        ALLO_ManageAllocations_CTRL ctrl = new ALLO_ManageAllocations_CTRL(
            new ApexPages.StandardSetController(new List<Allocation__c>())
        );

        system.assertEquals(2,ctrl.listAllo.size(),'The list of allocations should have two current campaign allocations.');

        ctrl.addRow();
        system.assertEquals(3,ctrl.listAllo.size(),'Adding a row increases the size of the allocation list.');

        //delete the first allocation on the list
        ctrl.rowNumber = 0;
        ctrl.delRow();

        ctrl.listAllo[1].Amount__c = 5;
        ctrl.listAllo[1].General_Accounting_Unit__c = gau.id;
        Test.startTest();
        ctrl.saveClose();
        Test.stopTest();

        list<Allocation__c> queryAllo = [SELECT Id, Percent__c, Amount__c FROM Allocation__c WHERE Recurring_Donation__c=:rd.id];
        system.assertEquals(2,queryAllo.size(),'2 allocations should be saved on the recurring donation; one original allocation should be deleted.');

        system.assertEquals(oppCnt * 2, [SELECT Count() FROM Allocation__c WHERE Opportunity__r.npe03__Recurring_Donation__c = :rd.Id],
                'There should still be two Allocations per Installment Opportunity');
    }

    /*******************************************************************************************************
    * @description Runs manage allocations page on a general allocation and verifies an
    * error is thrown when the page action to getPageLoadValidationmessages is called.
    ********************************************************************************************************/
    @isTest
    private static void testUnsupportedObject() {
        if (strTestOnly != '*' && strTestOnly != 'testUnsupportedObject') return;
        setupSettings(null);

        Account acc = new Account(Name='foo');
        insert acc;
        General_Accounting_Unit__c gau = new General_Accounting_Unit__c(Name = 'foo');
        insert gau;

        PageReference pageRef = Page.ALLO_ManageAllocations;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', gau.id);
        ALLO_ManageAllocations_CTRL ctrl = new ALLO_ManageAllocations_CTRL(
            new ApexPages.StandardSetController(new List<Allocation__c>())
        );
        ctrl.getPageLoadValidationMessages();
        List<Apexpages.Message> msgs = ApexPages.getMessages();
        Boolean errorFound = false;
        for (Apexpages.Message msg : msgs){
            if (msg.getDetail().contains(System.Label.alloObjectUnsupported)) errorFound = true;
        }
        System.assert(errorFound);
    }

    /*******************************************************************************************************
    * @description Runs manage allocations page on an opportunity and verifies an
    * error is not thrown when the page action to getPageLoadValidationmessages is called.
    ********************************************************************************************************/
    @isTest
    private static void testSupportedObject() {
        if (strTestOnly != '*' && strTestOnly != 'testUnsupportedObject') return;
        setupSettings(null);

        Account acc = new Account(Name='foo');
        insert acc;
        Opportunity opp = new Opportunity(Name='foo', Amount = 8, AccountID=acc.id, CloseDate=system.today(), StageName=UTIL_UnitTestData_TEST.getClosedWonStage());
        insert opp;
        General_Accounting_Unit__c gau = new General_Accounting_Unit__c(Name = 'foo');
        insert gau;

        PageReference pageRef = Page.ALLO_ManageAllocations;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', opp.id);
        ALLO_ManageAllocations_CTRL ctrl = new ALLO_ManageAllocations_CTRL(
            new ApexPages.StandardSetController(new List<Allocation__c>())
        );
        ctrl.getPageLoadValidationMessages();
        List<Apexpages.Message> msgs = ApexPages.getMessages();
        Boolean errorFound = false;
        for (Apexpages.Message msg : msgs){
            if (msg.getDetail().contains(System.Label.alloObjectUnsupported)) errorFound = true;
        }
        System.assert(!errorFound);
    }

    /*******************************************************************************************************
    * @description Runs manage allocations page on an opportunity with no amount and verifies an
    * error is thrown when the page action to getPageLoadValidationmessages is called.
    ********************************************************************************************************/
    @isTest
    private static void testOppNoAmount() {
        if (strTestOnly != '*' && strTestOnly != 'testUnsupportedObject') return;
        setupSettings(null);

        Account acc = new Account(Name='foo');
        insert acc;
        Opportunity opp = new Opportunity(Name='foo', AccountID=acc.id, CloseDate=system.today(), StageName=UTIL_UnitTestData_TEST.getClosedWonStage());
        insert opp;
        General_Accounting_Unit__c gau = new General_Accounting_Unit__c(Name = 'foo');
        insert gau;

        PageReference pageRef = Page.ALLO_ManageAllocations;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', opp.id);
        ALLO_ManageAllocations_CTRL ctrl = new ALLO_ManageAllocations_CTRL(
            new ApexPages.StandardSetController(new List<Allocation__c>())
        );
        ctrl.getPageLoadValidationMessages();
        List<Apexpages.Message> msgs = ApexPages.getMessages();
        Boolean errorFound = false;
        for (Apexpages.Message msg : msgs){
            if (msg.getDetail().contains(System.Label.alloCantAllocateNothing)) errorFound = true;
        }
        System.assert(errorFound);
    }

    /**
     * @description getCurrencySymbol() should return the appropriate currency
     * symbol as returned by UTIL_Currency
     */
    @isTest
    private static void testGetCurrencySymbolCallsUtilCurrency() {
        UTIL_Currency_TEST.UtilCurrencyMock mock = new UTIL_Currency_TEST.UtilCurrencyMock();
        mock.getCurrencySymbolReturn = 'FOO';
        UTIL_Currency.instance = mock;

        ALLO_ManageAllocations_CTRL controller = new ALLO_ManageAllocations_CTRL();
        controller.parentId = Account.sObjectType.getDescribe().getKeyPrefix() + '000000000001AAA';

        System.assertEquals(
            'FOO',
            controller.getCurrencySymbol()
        );

        System.assertEquals(
            controller.parentId,
            mock.getCurrencySymbolRecordId
        );
    }

    /**
     * @description getCurrencySymbol() should returned a cached currency
     * symbol, if it has been set
     */
    @isTest
    private static void testGetCurrencySymbolReturnsCachedSymbol() {
        ALLO_ManageAllocations_CTRL controller = new ALLO_ManageAllocations_CTRL();
        controller.currencySymbol = 'FOO';

        System.assertEquals(
            'FOO',
            controller.getCurrencySymbol()
        );
    }

    /** @description test the methods to retreive the currency separator characters */
    @isTest
    private static void testGetSeparators() {
        ALLO_ManageAllocations_CTRL controller = new ALLO_ManageAllocations_CTRL();
        system.AssertNotEquals(null, controller.getDecimalSeparator());
        system.AssertNotEquals(null, controller.getThousandsSeparator());
    }
}