src/objects/Allocation__c.object
<CustomObject>
    <fields>
        <fullName>General_Accounting_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The General Accounting Unit this Allocation is attributed to. Only General Accounting Units marked as active are available for new Allocations.</description>
        <inlineHelpText>The General Accounting Unit this Allocation is attributed to. Only General Accounting Units marked as active are available for new Allocations.</inlineHelpText>
        <label>General Accounting Unit</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <errorMessage>Choose an active General Accounting Unit for this Allocation. You cannot modify an Allocation assigned to an inactive General Accounting Unit.</errorMessage>
            <filterItems>
                <field>General_Accounting_Unit__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Payment__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.Payment__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>You must select an active General Accounting Unit for this Allocation.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>General_Accounting_Unit__c</referenceTo>
        <relationshipLabel>GAU Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity you want this Allocation attributed to. NPSP rolls up all Opportunities in a Closed/Won stage to this Allocation's General Accounting Unit.</description>
        <inlineHelpText>The Opportunity you want this Allocation attributed to. NPSP rolls up all Opportunities in a Closed/Won stage to this Allocation's General Accounting Unit.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>GAU Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GAU Allocation</label>
    <nameField>
        <displayFormat>ALL-{0}</displayFormat>
        <label>GAU Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GAU Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <description>Indicates if this Contact is designated as the Primary Contact on their Account (read only).</description>
        <formula>Account.npe01__One2OneContact__c = Id</formula>
        <inlineHelpText>Indicates if this Contact is designated as the Primary Contact on their Account (read only).</inlineHelpText>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/General_Accounting_Unit__c.object
<CustomObject>
    <description>Accounting units used for allocating Opportunities.</description>
    <label>General Accounting Unit</label>
    <nameField>
        <label>General Accounting Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Accounting Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/npe01__OppPayment__c.object
<CustomObject>
</CustomObject>

unpackaged/config/trial/objects/npe01__OppPayment__c.object
    <fields>
        <fullName>npe01__Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>OppPayment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Primary Contact for this Opportunity. If this is an individual Donation, NPSP attributes the Donation to the Primary Contact. If this is an organizational Donation, NPSP attributes a soft credit to the Primary Contact.</description>
        <inlineHelpText>The Primary Contact for this Opportunity. If this is an individual Donation, NPSP attributes the Donation to the Primary Contact. If this is an organizational Donation, NPSP attributes a soft credit to the Primary Contact.</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/CRLP_Rollup_TDTM.cls
/*
    Copyright (c) 2017, Salesforce.org
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Salesforce.org
* @date 2017
* @group Rollups
* @group-content ../../ApexDocContent/Rollups2.htm
* @description Customizable Rollups for TDTM
*
*/
public class CRLP_Rollup_TDTM extends TDTM_Runnable {

    /**
     * @description Trigger Handler on Opportunity, Payment and Allocation to determine if rollups to the parent
     * Account, Contact and/or GeneralAccountingUnit objects is necessary.
     * TODO Partial Soft Credits?
     * @param listNew the list of records from trigger new.
     * @param listOld the list of recods from trigger old.
     * @param triggerAction which trigger event (BeforeInsert, AfterInsert, etc.).
     * @param objResult the describe for the related object
     * @return dmlWrapper (null because this method never performs dml)
     */
    public override DmlWrapper run(List<SObject> newlist, List<SObject> oldlist,
            TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {

        // Don't continue if the Customizable Rollups engine is not enabled
        if (!CRLP_Rollup_SVC.isCustomizableRollupEngineEnabled) {
            return null;
        }

        List<SObject> recordsToRecalculate = new List<SObject>();
        for (Integer i=0; i < ((newlist == null ? oldlist.size() : newlist.size())); i++) {
            if (triggerAction == TDTM_Runnable.Action.AfterUpdate) {
                // Have any of the "key" fields on the record changed?
                if (isRollupRecalcNeeded(newlist[i], oldlist[i])) {
                    recordsToRecalculate.add(newlist[i]);
                }
            } else if (triggerAction == TDTM_Runnable.Action.AfterInsert || triggerAction == TDTM_Runnable.Action.AfterDelete ||
                    triggerAction == TDTM_Runnable.Action.AfterUndelete) {
                // Always recalculate after an Insert/Delete/Undelete
                recordsToRecalculate.add((newlist == null ? oldlist[i] : newlist[i]));
            }
        }

        // There are records to roll-up, so execute a queueable async process to start the work.
        if (!recordsToRecalculate.isEmpty()) {
            executeRollupsForSpecifiedRecords(recordsToRecalculate);
        }

        return null;
    }

    /**
     * @description Called by Update triggers to determine if a rollup recalculation is required for a given record
     * by examining only the specific fields referenced by rollups and filters for the specific SObject.
     * @param newRecord
     * @param oldRecord
     * @return Boolean
     */
    @TestVisible
    private static Boolean isRollupRecalcNeeded(SObject newRecord, SObject oldRecord) {

        // No old record, therefore always rolling up a new record
        if (oldRecord == null) {
            return true;
        }

        SObjectType objType = newRecord.getSObjectType();

        // Start by getting all the fields referenced by any Filter Group or active Rollup
        Set<Schema.DescribeFieldResult> fieldsToCompare = new Set<DescribeFieldResult>();
        fieldsToCompare.addAll(CMT_FilterRule_SEL.getReferencedFieldsByObject(objType));
        fieldsToCompare.addAll(CRLP_Rollup_SEL.getReferencedFieldsByObject(objType));

        // Loop through the FieldDescribeResults list and compare the value of each field between the
        // old and new objects.
        Boolean changed = false;
        for (DescribeFieldResult dfr : fieldsToCompare) {
            Object oldVal = oldRecord.get(dfr.name);
            Object newVal = newRecord.get(dfr.name);
            if (oldVal != newVal) {
                changed = true;
                break;
            }
        }
        return changed;
    }

    /**
     * @description For a give set of records that were inserted/updated/deleted/undeleted, determine the
     * parent Account/Contact/GAU Id's that require rolling up to and initiate the jobs that do those rollups
     * TODO - Add LDV support on the Account/Contact object
     * @param detailRecordsToRollup
     */
    private static void executeRollupsForSpecifiedRecords(List<SObject> detailRecordsToRollup) {
        SObjectType detailObjType = detailRecordsToRollup[0].getSObjectType();

        List<Id> accountIds = new List<Id>();
        List<Id> contactIds = new List<Id>();

        List<Opportunity> opps = new List<Opportunity>();
        if (detailObjType == Opportunity.SObjectType) {

            // Get all the Opportunities
            opps.addAll((List<Opportunity>) detailRecordsToRollup);

        } else if (detailObjType == npe01__OppPayment__c.SObjectType) {

            // If the payment records were modified, get the parent Opportunity records so that 
            // the linked AccountId and PrimaryContactId values can be retrieved for the rollups
            Set<Id> oppIds = new Set<Id>();
            for (SObject s  : detailRecordsToRollup) {
                npe01__OppPayment__c pmt = (npe01__OppPayment__c)s;
                if (pmt.npe01__Opportunity__c != null) {
                    oppIds.add(pmt.npe01__Opportunity__c);
                }
            }
            opps = [SELECT Id, AccountId, Primary_Contact__c FROM Opportunity WHERE Id IN :oppIds];

        } else if (detailObjType == Allocation__c.SObjectType) {

            // If the Allocation records were modified, get the parent GAU Id's to rollup
            List<Id> gauIds = new List<Id>();
            for (SObject s  : detailRecordsToRollup) {
                Allocation__c alloc = (Allocation__c)s;
                if (alloc.Opportunity__c != null) {
                    gauIds.add(alloc.General_Accounting_Unit__c);
                }
            }

            if (!accountIds.isEmpty()) {
                Integer batchSize = CRLP_Rollup_SVC.getLDVBatchSize(General_Accounting_Unit__c.SObjectType);
                Database.executeBatch(new CRLP_Rollup_BATCH_LDV(gauIds), batchSize);
            }
        }

        // If there are Opportunities, get the Account and/or Contact Ids to roll up to
        if (detailObjType != Allocation__c.SObjectType) {
            for (Opportunity opp : opps) {
                if (opp.AccountId != null) {
                    accountIds.add(opp.AccountId);
                }
                if (opp.Primary_Contact__c != null) {
                    contactIds.add(opp.Primary_Contact__c);
                }
            }

            // Account Rollup
            if (!accountIds.isEmpty()) {
                System.enqueueJob(new CRLP_RollupQueueable(accountIds));
            }
            // Contact Rollup
            if (!contactIds.isEmpty()) {
                System.enqueueJob(new CRLP_RollupQueueable(contactIds));
            }
        }
    }
}