src/objects/Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <description>The amount of the Opportunity allocated to this General Accounting Unit. Leave blank for percent-based Allocations.</description>
        <inlineHelpText>The amount of the Opportunity allocated to this General Accounting Unit. Leave blank for percent-based Allocations.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>General_Accounting_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The General Accounting Unit this Allocation is attributed to. Only General Accounting Units marked as active are available for new Allocations.</description>
        <inlineHelpText>The General Accounting Unit this Allocation is attributed to. Only General Accounting Units marked as active are available for new Allocations.</inlineHelpText>
        <label>General Accounting Unit</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <errorMessage>Choose an active General Accounting Unit for this Allocation. You cannot modify an Allocation assigned to an inactive General Accounting Unit.</errorMessage>
            <filterItems>
                <field>General_Accounting_Unit__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Payment__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.Payment__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>You must select an active General Accounting Unit for this Allocation.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>General_Accounting_Unit__c</referenceTo>
        <relationshipLabel>GAU Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity you want this Allocation attributed to. NPSP rolls up all Opportunities in a Closed/Won stage to this Allocation's General Accounting Unit.</description>
        <inlineHelpText>The Opportunity you want this Allocation attributed to. NPSP rolls up all Opportunities in a Closed/Won stage to this Allocation's General Accounting Unit.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>GAU Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GAU Allocation</label>
    <nameField>
        <displayFormat>ALL-{0}</displayFormat>
        <label>GAU Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GAU Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Allocations_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings for the allocation of Opportunities into General Accounting Units.</description>
    <fields>
        <fullName>Default_Allocations_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enabling Default Allocations creates an Allocation object for each Opportunity. This enables reporting on allocations to a default General Accounting Unit, but uses more data storage.</description>
        <inlineHelpText>Enabling Default Allocations creates an Allocation object for each Opportunity. This enables reporting on allocations to a default General Accounting Unit, but uses more data storage.</inlineHelpText>
        <label>Default Allocations Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <description>Holds the ID of the default General Accounting Unit for creation of default allocations or for the allocation of non allocated amounts.</description>
        <inlineHelpText>Holds the ID of the default General Accounting Unit for creation of default allocations or for the allocation of non allocated amounts.</inlineHelpText>
        <label>Default General Accounting Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Excluded_Opp_RecTypes__c</fullName>
        <description>Opportunity Record Types to exclude from calculations of Allocations rollups.</description>
        <inlineHelpText>Opportunity Record Types to exclude from calculations of Allocations rollups.</inlineHelpText>
        <label>Excluded Opp RecTypes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Excluded_Opp_Types__c</fullName>
        <description>Excluded Opportunity Types from Allocations rollups.</description>
        <inlineHelpText>Excluded Opportunity Types from Allocations rollups.</inlineHelpText>
        <label>Excluded Opp Types</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Allocations Settings</label>
</CustomObject>

src/objects/General_Accounting_Unit__c.object
<CustomObject>
    <description>Accounting units used for allocating Opportunities.</description>
    <label>General Accounting Unit</label>
    <nameField>
        <label>General Accounting Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Accounting Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ALLO_MakeDefaultAllocations_BATCH.cls
global class ALLO_MakeDefaultAllocations_BATCH implements Database.Batchable<sObject> {
    

/*
verify settings are enabled?
*/

    private Allocations_Settings__c alloSettings = UTIL_CustomSettingsFacade.getAllocationsSettings();
    private String query = 'SELECT Id, Amount FROM Opportunity';
    
    global ALLO_MakeDefaultAllocations_BATCH() {
        string strExcludeOppRecTypesQuery = '';
        string strExcludeOppTypesQuery = '';

        //build string of opp record type names for query
        if (alloSettings.Excluded_Opp_RecTypes__c != null) {
            strExcludeOppRecTypesQuery = ' WHERE RecordType.Name NOT IN ' + ALLO_Rollup_SCHED.convertToQueryListFormat(alloSettings.Excluded_Opp_Rectypes__c);
        }

        //build string of opp types for query
        if (alloSettings.Excluded_Opp_Types__c != null) {
            if (alloSettings.Excluded_Opp_RecTypes__c != null)
                strExcludeOppTypesQuery = ' AND ';
            else 
                strExcludeOppTypesQuery = ' WHERE ';
            strExcludeOppTypesQuery += ' Type NOT IN ' + ALLO_Rollup_SCHED.convertToQueryListFormat(alloSettings.Excluded_Opp_Types__c);
        }

        query += strExcludeOppRecTypesQuery + strExcludeOppTypesQuery;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {

        list<Opportunity> listOpps = (list<Opportunity>) scope;

        map<id,Opportunity> mapIdOpp = new map<id,Opportunity>();
        map<id,list<Allocation__c>> mapOppIdAllo = new map<id,list<Allocation__c>>();
        list<Allocation__c> listAlloForInsert = new list<Allocation__c>();
        list<Allocation__c> listAlloForUpdate = new list<Allocation__c>();

        for (Opportunity opp : listOpps) {
            mapIdOpp.put(opp.id, opp);
        }

        for (Allocation__c allo : [SELECT Id, General_Accounting_Unit__c, Opportunity__c, Amount__c FROM Allocation__c WHERE Opportunity__c IN :mapIdOpp.keySet()]) {
            if (!mapOppIdAllo.containsKey(allo.Opportunity__c)) 
                mapOppIdAllo.put(allo.Opportunity__c, new list<Allocation__c>());

            mapOppIdAllo.get(allo.Opportunity__c).add(allo);
        }

        for (Opportunity opp : listOpps) {
            //if we have allocations for this opp, create or update the default
            if (mapOppIdAllo.containsKey(opp.id)) {
                decimal remainder = opp.Amount;
                Allocation__c defaultAllo = new Allocation__c();

                for (Allocation__c allo : mapOppIdAllo.get(opp.id)) {
                    if (alloSettings.Default_Allocations_Enabled__c && allo.General_Accounting_Unit__c == alloSettings.Default__c)
                        defaultAllo = allo;
                    else
                        remainder -= allo.Amount__c;
                }

                if (remainder > 0) {
                    if (defaultAllo.id!=null && defaultAllo.Amount__c!=remainder) {
                        defaultAllo.Amount__c = remainder;
                        listAlloForUpdate.add(defaultAllo);
                    } else if (defaultAllo.id==null) {
                        listAlloForInsert.add(new Allocation__c(
                            Opportunity__c = opp.id,
                            Amount__c = remainder,
                            General_Accounting_Unit__c = alloSettings.Default__c
                        ));
                    }
                }
            //if we have no allocations for this opp, create one
            } else {
                listAlloForInsert.add(new Allocation__c(
                    Opportunity__c = opp.id,
                    Amount__c = opp.Amount,
                    General_Accounting_Unit__c = alloSettings.Default__c
                ));
            }
        }

        if (!listAlloForInsert.isEmpty()) {
            ALLO_Allocations_TDTM.resetFlags(true);
            insert listAlloForInsert;
        }
        if (!listAlloForUpdate.isEmpty()) {
            ALLO_Allocations_TDTM.resetFlags(true);
            update listAlloForUpdate;
        }
    }
    
    global void finish(Database.BatchableContext BC) {}
    
}