src/objects/Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <description>The amount of the Opportunity allocated to this General Accounting Unit. Leave blank for percent-based Allocations.</description>
        <inlineHelpText>The amount of the Opportunity allocated to this General Accounting Unit. Leave blank for percent-based Allocations.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Campaign associated with this Allocation. Use this field if you want new Opportunities associated with this Campaign to be allocated in the same way.</description>
        <inlineHelpText>The Campaign associated with this Allocation. Use this field if you want new Opportunities associated with this Campaign to be allocated in the same way.</inlineHelpText>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>GAU Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>General_Accounting_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The General Accounting Unit this Allocation is attributed to. Only General Accounting Units marked as active are available for new Allocations.</description>
        <inlineHelpText>The General Accounting Unit this Allocation is attributed to. Only General Accounting Units marked as active are available for new Allocations.</inlineHelpText>
        <label>General Accounting Unit</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <errorMessage>Choose an active General Accounting Unit for this Allocation. You cannot modify an Allocation assigned to an inactive General Accounting Unit.</errorMessage>
            <filterItems>
                <field>General_Accounting_Unit__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Payment__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.Payment__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>You must select an active General Accounting Unit for this Allocation.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>General_Accounting_Unit__c</referenceTo>
        <relationshipLabel>GAU Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity you want this Allocation attributed to. NPSP rolls up all Opportunities in a Closed/Won stage to this Allocation's General Accounting Unit.</description>
        <inlineHelpText>The Opportunity you want this Allocation attributed to. NPSP rolls up all Opportunities in a Closed/Won stage to this Allocation's General Accounting Unit.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>GAU Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recurring_Donation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Recurring Donation this Allocation is attributed to. NPSP automatically allocates all new Opportunities associated with the Recurring Donation in the same way.</description>
        <inlineHelpText>The Recurring Donation this Allocation is attributed to. NPSP automatically allocates all new Opportunities associated with the Recurring Donation in the same way.</inlineHelpText>
        <label>Recurring Donation</label>
        <referenceTo>npe03__Recurring_Donation__c</referenceTo>
        <relationshipLabel>GAU Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GAU Allocation</label>
    <nameField>
        <displayFormat>ALL-{0}</displayFormat>
        <label>GAU Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GAU Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Error__c.object
<CustomObject>
    <description>Contains errors generated from the NPSP package during normal operations.</description>
    <label>Error</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Error Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error__c/fields/Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Object_Type__c</fullName>
    <description>Type of object on which the error occurred, if known.</description>
    <inlineHelpText>Type of object on which the error occurred, if known.</inlineHelpText>
    <label>Object Type</label>
    <type>TextArea</type>
</CustomField>

src/objects/npe03__Recurring_Donation__c.object
<CustomObject>
</CustomObject>

unpackaged/config/trial/objects/npe03__Recurring_Donation__c.object
    <fields>
        <fullName>npe03__Amount__c</fullName>
        <description>The amount for each installment Opportunity.</description>
        <inlineHelpText>The amount for each installment Opportunity.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

unpackaged/config/trial/objects/npe03__Recurring_Donation__c.object
    <fields>
        <fullName>npe03__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N80000002bOmREAU</relationshipName>
        <type>Lookup</type>
    </fields>

unpackaged/config/trial/objects/npe03__Recurring_Donation__c.object
    <fields>
        <fullName>npe03__Date_Established__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The initial inception date for this Recurring Donation. The default is the current date.</description>
        <inlineHelpText>The initial inception date for this recurring donation. The default is the current date.</inlineHelpText>
        <label>Date Established</label>
        <type>Date</type>
    </fields>

unpackaged/config/trial/objects/npe03__Recurring_Donation__c.object
    <fields>
        <fullName>npe03__Installment_Period__c</fullName>
        <description>How often you’ll receive the donations. NOTE: Changing the installment period for an existing Fixed-Length Recurring Donation may result in the loss and re-creation of open opportunities. Any data associated with those opportunities may be lost.</description>
        <inlineHelpText>The Installment Period along with Installment Frequency defines the installment schedule of this Recurring Donation. For example, if Installment Period is Monthly and Installment Frequency is 3, the schedule is defined as &quot;every 3 months&quot;.</inlineHelpText>
        <label>Installment Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                    <default>true</default>
                    <label>Monthly</label>
                </value>
                <value>
                    <fullName>Yearly</fullName>
                </value>
                <value>
                    <fullName>Weekly</fullName>
                </value>
                <value>
                    <fullName>1st and 15th</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

unpackaged/config/trial/objects/npe03__Recurring_Donation__c.object
    <fields>
        <fullName>npe03__Installments__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Number of installments (donations) you expect to receive. For Fixed-Length Recurring Donations only.</description>
        <inlineHelpText>Number of installments.  Only used with Non-Open Ended Recurring Donations.</inlineHelpText>
        <label>Number of Planned Installments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

unpackaged/config/trial/objects/npe03__Recurring_Donation__c.object
    <fields>
        <fullName>npe03__Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Recurring Donations</relationshipLabel>
        <relationshipName>RecurringDonations</relationshipName>
        <type>Lookup</type>
    </fields>

unpackaged/config/trial/objects/npe03__Recurring_Donation__c.object
    <fields>
        <fullName>npe03__Schedule_Type__c</fullName>
        <description>Tells Salesforce how to compute the amount for each child opportunity, based on what you&apos;ve entered in the Amount field. For Fixed-Length Recurring Donations only.</description>
        <inlineHelpText>Whether the Amount is used for each installment (Multiple By), or Amount is split between installments (Divide By).  Only used with Non-Open Ended Recurring Donations.</inlineHelpText>
        <label>Schedule Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Multiply By</fullName>
                </value>
                <value>
                    <fullName>Divide By</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/npe4__Relationship__c.object
<CustomObject>
</CustomObject>

unpackaged/config/trial/objects/npe4__Relationship__c.object
    <fields>
        <fullName>npe4__Contact__c</fullName>
        <description>Related Contact is this Contact&apos;s ______.</description>
        <inlineHelpText>Related Contact is this Contact&apos;s ______.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>

unpackaged/config/trial/objects/npe4__Relationship__c.object
    <fields>
        <fullName>npe4__RelatedContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Hidden Relationships List</relationshipLabel>
        <relationshipName>Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>

unpackaged/config/trial/objects/npe4__Relationship__c.object
    <fields>
        <fullName>npe4__Status__c</fullName>
        <description>Status of the Relationship.</description>
        <inlineHelpText>Status of the Relationship.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Former</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

unpackaged/config/trial/objects/npe4__Relationship__c.object
    <fields>
        <fullName>npe4__Type__c</fullName>
        <description>Field that describes how the Related Contact is connected to the Contact.</description>
        <inlineHelpText>Field that describes how the Related Contact is connected to the Contact.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Family</fullName>
                </value>
                <value>
                    <fullName>Coworker</fullName>
                </value>
                <value>
                    <fullName>Father</fullName>
                </value>
                <value>
                    <fullName>Mother</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Son</fullName>
                </value>
                <value>
                    <fullName>Daughter</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Husband</fullName>
                </value>
                <value>
                    <fullName>Wife</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Grandmother</fullName>
                </value>
                <value>
                    <fullName>Grandfather</fullName>
                </value>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
                <value>
                    <fullName>Grandson</fullName>
                </value>
                <value>
                    <fullName>Granddaughter</fullName>
                </value>
                <value>
                    <fullName>Grandchild</fullName>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/classes/CDL_CascadeDeleteLookups_TEST.cls
/*
    Copyright (c) 2016, Salesforce.org
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Salesforce.org
* @date 2016
* @group Cascade Delete
* @description Cascade Delete test data factory.
*/
@isTest
public class CDL_CascadeDeleteLookups_TEST {

    /*******************************************************************************************************
    * @description Creates Accounts.
    * @param Integer The maximum records to create.
    * @return List<Account> The created Accounts.
    ********************************************************************************************************/
    public static List<Account> buildAccounts(Integer maxRecords) {
        List<Account> result = new List<Account>();
        for (Integer i = 0; i < maxRecords; i++) {
            result.add(new Account(Name = 'Account' + i));
        }
        return result;
    }

    /*******************************************************************************************************
    * @description Creates Contacts.
    * @param Integer The maximum records to create.
    * @return List<Contact> The created Contacts.
    ********************************************************************************************************/
    public static List<Contact> buildContacts(Integer maxRecords) {
        List<Contact> result = new List<Contact>();
        for (Integer i = 0; i < maxRecords; i++) {
            result.add(new Contact(LastName = 'CONTACT' + i));
        }
        return result;
    }

    /*******************************************************************************************************
    * @description Creates Contact Recurring Donations.
    * @param List<Contact> The Contacts records that are used to create the Recurring Donations.
    * @return List<npe03__Recurring_Donation__c> The created Contact Recurring Donations.
    ********************************************************************************************************/
    public static List<npe03__Recurring_Donation__c> buildContactRDs(List<Contact> testContacts) {
        List<npe03__Recurring_Donation__c> result = new List<npe03__Recurring_Donation__c>();
        for (Contact testContact : testContacts) {
            result.add(
                new npe03__Recurring_Donation__c(
                    Name = 'CON_RD',
                    npe03__Installments__c = 2,
                    npe03__Amount__c = 1,
                    npe03__Installment_Period__c = System.Label.npe03.RecurringDonationInstallmentPeriodYearly,
                    npe03__Date_Established__c = Date.newinstance(1970,6,12),
                    npe03__Schedule_Type__c = System.Label.npe03.RecurringDonationMultiplyValue,
                    npe03__Contact__c = testContact.Id
                )
            );
        }
        return result;
    }

    /*******************************************************************************************************
    * @description Creates Organizational Recurring Donations.
    * @param List<Account> The Accounts records that are used to create the Recurring Donations.
    * @return List<npe03__Recurring_Donation__c> The created Organizational Recurring Donations.
    ********************************************************************************************************/
    public static List<npe03__Recurring_Donation__c> buildOrganizationalRDs(List<Account> testAccounts) {
        List<npe03__Recurring_Donation__c> result = new List<npe03__Recurring_Donation__c>();
        for (Account testAccount : testAccounts) {
            result.add(
                new npe03__Recurring_Donation__c(
                    Name = 'ORG_RD' + testAccount.Name,
                    npe03__Installments__c = 2,
                    npe03__Amount__c = 1,
                    npe03__Installment_Period__c = System.Label.npe03.RecurringDonationInstallmentPeriodYearly,
                    npe03__Date_Established__c = Date.newinstance(1970,6,12),
                    npe03__Schedule_Type__c = System.Label.npe03.RecurringDonationMultiplyValue,
                    npe03__Organization__c = testAccount.Id
                )
            );
        }
        return result;
    }

    /*******************************************************************************************************
    * @description Creates Opportunities.
    * @param List<Account> The Accounts records that are used to create the Opportunities.
    * @return List<Opportunity> The created Opportunities.
    ********************************************************************************************************/
    public static List<Opportunity> buildOpportunities(List<Account> testAccounts) {
        List<Opportunity> result = new List<Opportunity>();
        for (Account testAccount : testAccounts) {
            result.add(
                new Opportunity(
                    Name = 'OPP_' + testAccount.Name,
                    Amount = 8,
                    AccountId = testAccount.Id,
                    StageName = UTIL_UnitTestData_TEST.getClosedLostStage(),
                    CloseDate = System.today()
                )
            );
        }
        return result;
    }

    /*******************************************************************************************************
    * @description Creates Recurring Donation Opportunities.
    * @param List<npe03__Recurring_Donation__c> The Recurring Donations that are used to create the Opportunities.
    * @return List<Opportunity> The created Opportunities.
    ********************************************************************************************************/
    public static List<Opportunity> buildRDOpportunities(List<npe03__Recurring_Donation__c> testRecurringDonations, String stageName) {
        List<Opportunity> result = new List<Opportunity>();
        for (npe03__Recurring_Donation__c testRecurringDonation : testRecurringDonations) {
            result.add(
                new Opportunity(
                    Name = 'OPP_' + testRecurringDonation.Name,
                    Amount = 8,
                    AccountId = testRecurringDonation.npe03__Organization__c,
                    StageName = stageName,
                    CloseDate = System.today(),
                    npe03__Recurring_Donation__c = testRecurringDonation.Id
                )
            );
        }
        return result;
    }

    /*******************************************************************************************************
    * @description Creates Recurring Donation Allocations.
    * @param General_Accounting_Unit__c The General Accounting Unit record that is used to create the Allocations.
    * @param List<npe03__Recurring_Donation__c> The Recurring Donations records that are used to create the Allocations.
    * @return List<Allocation__c> The created Allocations.
    ********************************************************************************************************/
    public static List<Allocation__c> buildRDAllocations(General_Accounting_Unit__c testGAU,  List<npe03__Recurring_Donation__c> testRecurringDonations) {
        List<Allocation__c> result = new List<Allocation__c>();
        for (npe03__Recurring_Donation__c testRecurringDonation : testRecurringDonations) {
            result.add(
                new Allocation__c(
                    Amount__c = 4, 
                    Recurring_Donation__c = testRecurringDonation.Id,
                    General_Accounting_Unit__c = testGAU.Id
                )
            );
        }
        return result;
    }

    /*******************************************************************************************************
    * @description Creates Opportunity Allocations.
    * @param General_Accounting_Unit__c The General Accounting Unit record that is used to create the Allocations.
    * @param List<Opportunity> The Opportunities records that are used to create the Allocations.
    * @return List<Allocation__c> The created Allocations.
    ********************************************************************************************************/
    public static List<Allocation__c> buildOpportunityAllocations(General_Accounting_Unit__c testGAU,  List<Opportunity> testOpportunities) {
        List<Allocation__c> result = new List<Allocation__c>();
        for (Opportunity testOpportunity : testOpportunities) {
            result.add(
                new Allocation__c(
                    Amount__c = 4, 
                    Opportunity__c = testOpportunity.Id,
                    General_Accounting_Unit__c = testGAU.Id
                )
            );
        }
        return result;
    }

    /*******************************************************************************************************
    * @description Creates Relationships.
    * @param List<Contact> The Contacts records that are used to create the Relationships.
    * @return List<npe4__Relationship__c> The created Relationships.
    ********************************************************************************************************/
    public static List<npe4__Relationship__c> buildRelationships(List<Contact> testContacts) {
        List<npe4__Relationship__c> result = new List<npe4__Relationship__c>();

        Map<Id, Contact> testContactsWithFriends = new Map<Id, Contact>();
        for (Contact testContact : testContacts) {
            testContactsWithFriends.put(testContact.Id, new Contact(LastName = 'FRIEND_OF_' + testContact.LastName));
        }
        insert testContactsWithFriends.values();

        for (Contact testContact : testContacts) {
            result.add(
                new npe4__Relationship__c(
                    npe4__contact__c = testContact.Id, 
                    npe4__relatedcontact__c = testContactsWithFriends.get(testContact.Id).Id, 
                    npe4__Type__c = 'Friend',
                    npe4__Status__c = 'Active'
                )
            );
        }
        return result;
    }

    /*******************************************************************************************************
    * @description Creates Campaigns.
    * @param Integer The maximum records to create.
    * @return List<Campaign> The created Campaigns.
    ********************************************************************************************************/
    public static List<Campaign> buildCampaigns(Integer maxRecords) {
        List<Campaign> result = new List<Campaign>();
        for (Integer i = 0; i < maxRecords; i++) {
            result.add(new Campaign(Name = 'CAMP' + i));
        }
        return result;
    }

    /*******************************************************************************************************
    * @description Creates Campaign Allocations.
    * @param General_Accounting_Unit__c The General Accounting Unit record that is used to create the Allocations.
    * @param List<Campaign> The Campaigns records that are used to create the Allocations.
    * @return List<Allocation__c> The created Allocations.
    ********************************************************************************************************/
    public static List<Allocation__c> buildCampaignAllocations(General_Accounting_Unit__c testGAU,  List<Campaign> testCampaigns) {
        List<Allocation__c> result = new List<Allocation__c>();
        for (Campaign testCampaign : testCampaigns) {
            result.add(
                new Allocation__c(
                    Amount__c = 4, 
                    Campaign__c = testCampaign.Id,
                    General_Accounting_Unit__c = testGAU.Id
                )
            );
        }
        return result;
    }

    /*******************************************************************************************************
    * @description Gets the deleted Recurring Donations.
    * @return List<npe03__Recurring_Donation__c> The List of deleted Recurring Donations.
    ********************************************************************************************************/
    public static List<npe03__Recurring_Donation__c> getDeletedRecurringDonations() {
        return [
            SELECT Id 
            FROM npe03__Recurring_Donation__c
            WHERE IsDeleted = true 
            ALL ROWS
        ];
    }

    /*******************************************************************************************************
    * @description Gets the non deleted Recurring Donations.
    * @return List<npe03__Recurring_Donation__c> The List of non deleted Recurring Donations.
    ********************************************************************************************************/
    public static List<npe03__Recurring_Donation__c> getNonDeletedRecurringDonations() {
        return [
            SELECT Id 
            FROM npe03__Recurring_Donation__c 
            WHERE IsDeleted = false
        ];
    }

    /*******************************************************************************************************
    * @description Gets the deleted Allocations.
    * @return List<Allocation__c> The List of deleted Allocations.
    ********************************************************************************************************/
    public static List<Allocation__c> getDeletedAllocations() {
        return [
            SELECT Id 
            FROM Allocation__c 
            WHERE IsDeleted = true 
            ALL ROWS
        ];
    }

    /*******************************************************************************************************
    * @description Gets the non deleted Allocations.
    * @return List<Allocation__c> The List of non deleted Allocations.
    ********************************************************************************************************/
    public static List<Allocation__c> getNonDeletedAllocations() {
        return [
            SELECT Id 
            FROM Allocation__c 
            WHERE IsDeleted = false
        ];
    }

    /*******************************************************************************************************
    * @description Gets the deleted Relationships.
    * @return List<npe4__Relationship__c> The List of deleted Relationships.
    ********************************************************************************************************/
    public static List<npe4__Relationship__c> getDeletedRelationships() {
        return [
            SELECT Id 
            FROM npe4__Relationship__c
            WHERE IsDeleted = true 
            ALL ROWS 
        ];
    }

    /*******************************************************************************************************
    * @description Gets the non deleted Relationships.
    * @return List<npe4__Relationship__c> The List of deleted Relationships.
    ********************************************************************************************************/
    public static List<npe4__Relationship__c> getNonDeletedRelationships() {
        return [
            SELECT Id 
            FROM npe4__Relationship__c
            WHERE IsDeleted = false
        ];
    }

    /*******************************************************************************************************
    * @description Gets the deleted Opportunities.
    * @return List<Opportunity> The List of deleted Opportunities.
    ********************************************************************************************************/
    public static List<Opportunity> getDeletedOpportunities() {
        return [
            SELECT Id 
            FROM Opportunity
            WHERE IsDeleted = true 
            ALL ROWS 
        ];
    }

    /*******************************************************************************************************
    * @description Gets the non deleted Opportunities.
    * @return List<Opportunity> The List of deleted Opportunities.
    ********************************************************************************************************/
    public static List<Opportunity> getNonDeletedOpportunities() {
        return [
            SELECT Id 
            FROM Opportunity
            WHERE IsDeleted = false
        ];
    }

    /*******************************************************************************************************
    * @description Gets the errors.
    * @return List<Error__c> The List of errors.
    ********************************************************************************************************/
    public static List<Error__c> getErrors() {
        return [
            SELECT Id, Object_Type__c, Full_Message__c, Stack_Trace__c 
            FROM Error__c
        ];
    }
}