src/objects/Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <description>The amount of the Opportunity allocated to this General Accounting Unit. Leave blank for percent-based Allocations.</description>
        <inlineHelpText>The amount of the Opportunity allocated to this General Accounting Unit. Leave blank for percent-based Allocations.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>General_Accounting_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The General Accounting Unit this Allocation is attributed to. Only General Accounting Units marked as active are available for new Allocations.</description>
        <inlineHelpText>The General Accounting Unit this Allocation is attributed to. Only General Accounting Units marked as active are available for new Allocations.</inlineHelpText>
        <label>General Accounting Unit</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <errorMessage>Choose an active General Accounting Unit for this Allocation. You cannot modify an Allocation assigned to an inactive General Accounting Unit.</errorMessage>
            <filterItems>
                <field>General_Accounting_Unit__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.Payment__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <filterItems>
                <field>$Source.Payment__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>You must select an active General Accounting Unit for this Allocation.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>General_Accounting_Unit__c</referenceTo>
        <relationshipLabel>GAU Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Opportunity you want this Allocation attributed to. NPSP rolls up all Opportunities in a Closed/Won stage to this Allocation's General Accounting Unit.</description>
        <inlineHelpText>The Opportunity you want this Allocation attributed to. NPSP rolls up all Opportunities in a Closed/Won stage to this Allocation's General Accounting Unit.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>GAU Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Attributes allocations to a Payment.</description>
        <inlineHelpText>Attributes allocations to a Payment.</inlineHelpText>
        <label>Payment</label>
        <referenceTo>npe01__OppPayment__c</referenceTo>
        <relationshipLabel>Payment Allocations</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Percent__c</fullName>
        <description>Percent of Opportunity amount allocated to this Allocation's General Accounting Unit. If you later modify the Opportunity amount, NPSP will update the allocation amount on the General Accounting Unit.</description>
        <inlineHelpText>Percent of Opportunity amount allocated to this Allocation's General Accounting Unit. If you later modify the Opportunity amount, NPSP will update the allocation amount on the General Accounting Unit.</inlineHelpText>
        <label>Percent</label>
        <precision>9</precision>
        <scale>6</scale>
        <type>Percent</type>
    </fields>
    <label>GAU Allocation</label>
    <nameField>
        <displayFormat>ALL-{0}</displayFormat>
        <label>GAU Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GAU Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Allocations_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings for the allocation of Opportunities into General Accounting Units.</description>
    <fields>
        <fullName>Default_Allocations_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enabling Default Allocations creates an Allocation object for each Opportunity. This enables reporting on allocations to a default General Accounting Unit, but uses more data storage.</description>
        <inlineHelpText>Enabling Default Allocations creates an Allocation object for each Opportunity. This enables reporting on allocations to a default General Accounting Unit, but uses more data storage.</inlineHelpText>
        <label>Default Allocations Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <description>Holds the ID of the default General Accounting Unit for creation of default allocations or for the allocation of non allocated amounts.</description>
        <inlineHelpText>Holds the ID of the default General Accounting Unit for creation of default allocations or for the allocation of non allocated amounts.</inlineHelpText>
        <label>Default General Accounting Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Allocations Settings</label>
</CustomObject>

force-app/main/default/objects/Allocations_Settings__c/fields/Payment_Allocations_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Payment_Allocations_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether Allocations can be set at the Payment level. If selected, you can manually create Allocation records for each Payment, or let NPSP automatically create Payment Allocation records based on the related Opportunity Allocation settings.</description>
    <inlineHelpText>Indicates whether Allocations can be set at the Payment Level. Only for use with Accounting Subledger. Contact your Salesforce Account Executive for more information.</inlineHelpText>
    <label>Payment Allocations Enabled</label>
    <type>Checkbox</type>
</CustomField>

src/objects/General_Accounting_Unit__c.object
<CustomObject>
    <description>Accounting units used for allocating Opportunities.</description>
    <label>General Accounting Unit</label>
    <nameField>
        <label>General Accounting Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Accounting Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/npe01__OppPayment__c.object
<CustomObject>
</CustomObject>

unpackaged/config/trial/objects/npe01__OppPayment__c.object
    <fields>
        <fullName>npe01__Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>OppPayment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>

unpackaged/config/trial/objects/npe01__OppPayment__c.object
    <fields>
        <fullName>npe01__Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

unpackaged/config/trial/objects/npe01__OppPayment__c.object
    <fields>
        <fullName>npe01__Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>

src/objects/Opportunity.object
<CustomObject>
</CustomObject>

unpackaged/config/qa/objects/Opportunity.object
    <fields>
        <fullName>npe01__Do_Not_Automatically_Create_Payment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If payments are active, and if this is checked, a new payment will not be automatically created for this Opportunity.</description>
        <inlineHelpText>If payments are active, and if checked, a new payment will not be automatically created for this Opportunity.</inlineHelpText>
        <label>Do Not Automatically Create Payment</label>
        <type>Checkbox</type>
    </fields>

src/classes/ALLO_PaymentSync_TEST.cls
/*
    Copyright (c) 2019, Salesforce.org
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Salesforce.org
* @date 2019
* @group Allocations
* @group-content ../../ApexDocContent/Allocations.htm
* @description Tests specific to Allocations trigger based functionality. 
*/
@isTest
private with sharing  class ALLO_PaymentSync_TEST {
//TODO null and zero amounts for both opps and payments
//TODO negative payment amounts
//TODO over and underscheduled

    static General_Accounting_Unit__c defaultGau;
    static List<General_Accounting_Unit__c> gaus = new List<General_Accounting_Unit__c>();

    static Opportunity opportunity;
    static List<npe01__OppPayment__c> payments = new List<npe01__OppPayment__c>();

    @testSetup 
    static void setup() {
        General_Accounting_Unit__c gau = new General_Accounting_Unit__c(Name='Default GAU');
        insert gau;

        Account account = new Account(Name='Account');
        insert account;

        Opportunity opportunity = new Opportunity(
            Name = 'Opp', 
            Amount = 1000, 
            AccountID = account.Id, 
            CloseDate = System.today(), 
            StageName = UTIL_UnitTestData_TEST.getClosedWonStage(),
            npe01__Do_Not_Automatically_Create_Payment__c = true
        );
        insert opportunity;

    }

    /*******************************************************************************************************
    * @description When changing the amount of a Payment with Allocations: 
    * Increasing the amount will adjust the percentage allocations.
    * Decreasing the amount so that the total allocation amount is below the payment amount will adjust 
    * the percentage allocations.
    * Decreasing the amount so that the total allocation amount is greater than the payment amount, an 
    * error is thrown and the payment update is blocked.
    ********************************************************************************************************/
    @isTest
    static void syncPaymentToOpportunity() {
        makePayments(1000, 1);
        makeGAUs(2);

        System.assert(UTIL_CustomSettingsFacade.getAllocationsSettings().Payment_Allocations_Enabled__c, UTIL_CustomSettingsFacade.getAllocationsSettings());

        //resetting these manually as a test is considered a single context for static variables
        List<Allocation__c> alloForInsert = new List<Allocation__c>();

        Allocation__c percentAllo = new Allocation__c(Payment__c=payments[0].id, Percent__c = 50, General_Accounting_Unit__c = gaus[0].id);
        alloForInsert.add(percentAllo);
        Allocation__c amountAllo = new Allocation__c(Payment__c=payments[0].id, Amount__c = 300, General_Accounting_Unit__c = gaus[1].id);
        alloForInsert.add(amountAllo);
        insert alloForInsert;

        List<Allocation__c> queryAllocations = getAllocationsOrderByAmount();
        System.assertEquals(6, queryAllocations.size(), 'Six opportunity allocations should exist.');
        //synced opportunity allocations
        assertAllocation(queryAllocations[0], 200, defaultGau.Id, true);
        assertAllocation(queryAllocations[1], 300, gaus[1].id, true);
        assertAllocation(queryAllocations[2], 500, gaus[0].id, true);
        //original payment allocations
        assertAllocation(queryAllocations[3], 200, defaultGau.Id, false);
        assertAllocation(queryAllocations[4], 300, gaus[1].id, false);
        assertAllocation(queryAllocations[5], 500, gaus[0].id, false);
    }

    /*******************************************************************************************************
    * @description When changing the Allocation amount of an Opportunity with Payments:
    * Increasing the amount will adjust the percentage allocations.
    * Decreasing the amount so that the total allocation amount is below the payment amount will adjust 
    * the percentage allocations.
    * Decreasing the amount so that the total allocation amount is greater than the payment amount, an 
    * error is thrown and the payment update is blocked.
    ********************************************************************************************************/
    @isTest
    static void syncOpportunityToPayment() {
        makePayments(1000, 1);
        makeGAUs(2);

        //resetting these manually as a test is considered a single context for static variables
        List<Allocation__c> alloForInsert = new List<Allocation__c>();

        Allocation__c percentAllo = new Allocation__c(Opportunity__c=opportunity.id, Percent__c = 50, General_Accounting_Unit__c = gaus[0].id);
        alloForInsert.add(percentAllo);
        Allocation__c amountAllo = new Allocation__c(Opportunity__c=opportunity.id, Amount__c = 300, General_Accounting_Unit__c = gaus[1].id);
        alloForInsert.add(amountAllo);
        insert alloForInsert;

        List<Allocation__c> queryAllocations = getAllocationsOrderByAmount();
        System.assertEquals(6, queryAllocations.size(), 'Six allocations should exist.');
        //original opportunity allocations
        assertAllocation(queryAllocations[0], 200, defaultGau.Id, true);
        assertAllocation(queryAllocations[1], 300, gaus[1].id, true);
        assertAllocation(queryAllocations[2], 500, gaus[0].id, true);
        //synced payment allocations
        assertAllocation(queryAllocations[3], 200, defaultGau.Id, false);
        assertAllocation(queryAllocations[4], 300, gaus[1].id, false);
        assertAllocation(queryAllocations[5], 500, gaus[0].id, false);
    }

//TODO can't update opportunity and payment allocations for the same opportunity (only substantial updates)
    @isTest
    private static void validateOverlappingChanges() {

    }

    // Helpers
    ////////////
    private static void makePayments(Decimal totalAmount, Integer numberOfPayments) {
        defaultGau = [SELECT Id FROM General_Accounting_Unit__c WHERE Name = 'Default GAU' LIMIT 1];
        opportunity = [SELECT Id, Name, Amount FROM Opportunity LIMIT 1];

        UTIL_CustomSettingsFacade.getAllocationsSettingsForTests(
            new Allocations_Settings__c(
                Payment_Allocations_Enabled__c = true,
                Default_Allocations_Enabled__c = true,
                Default__c = defaultGau.Id
            )
        );

        for (Integer i=0; i<numberOfPayments; i++) {
            payments.add(new npe01__OppPayment__c(
                npe01__Payment_Amount__c = totalAmount / numberOfPayments, 
                npe01__Opportunity__c = opportunity.Id,
                npe01__Payment_Date__c = System.today()
            ));
        }
        insert payments;
    } 

    private static void makeGAUs(Integer numberOfGAUs) {
        for (Integer i=0; i<numberOfGAUs; i++) {
            gaus.add(new General_Accounting_Unit__c(Name='GAU' + i));
        }
        insert gaus;
    }

    private static void assertAllocation(Allocation__c allocation, Decimal amount, Id gau, Boolean isOpportunityAllocation) {
        System.assertEquals(amount, allocation.Amount__c, 'Allocation amount mismatch: ' + allocation);
        System.assertEquals(gau, allocation.General_Accounting_Unit__c, 'Allocation GAU mismatch: ' + allocation);
        System.assertEquals(isOpportunityAllocation, allocation.Opportunity__c != null, 'Allocation type mismatch: ' + allocation);
    }
    /*********************************************************************************************************
    * @description Get all Allocations ordered by Amount
    * @return List<Allocation__c> A list of all Allocations 
    **********************************************************************************************************/
    private static List<Allocation__c> getAllocationsOrderByAmount() {
        return Database.query(getAllocationsQuery().build() + ' ORDER BY Payment__c, Amount__c');
    }

    /*********************************************************************************************************
    * @description Get all Allocations ordered by Percent
    * @return List<Allocation__c> A list of all Allocations 
    **********************************************************************************************************/
    private static List<Allocation__c> getAllocationsOrderByPercent() {
        return Database.query(getAllocationsQuery().build() + ' ORDER BY Payment__c, Percent__c');
    }

    /*********************************************************************************************************
    * @description Build query to retrieve all Allocations
    * @return UTIL_Query Allocation SOQL
    **********************************************************************************************************/
    private static UTIL_Query getAllocationsQuery() {
        return new UTIL_Query()
            .withSelectFields(new String[]{
                'Opportunity__c',
                'Payment__c',
                'General_Accounting_Unit__c', 
                'General_Accounting_Unit__r.Name', 
                'Amount__c', 
                'Percent__c' 
            })
            .withFrom('Allocation__c');
    }
}