src/objects/Batch_Data_Entry_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Batch Data Entry Settings</label>
</CustomObject>

force-app/main/default/objects/Batch_Data_Entry_Settings__c/fields/Viewed_Retirement_Alert__c.field-meta.xml
<CustomField>
    <fullName>Viewed_Retirement_Alert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Viewed Retirement Alert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BDE_BatchEntry_TEST.cls
/*
    Copyright (c) 2015 Salesforce.org
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Team Kick Ass; Veronica Waters, Evan Callahan, Derek Dsouza, Mike Fullmore
* @date 04/27/2011
* @group BatchDataEntry
* @description test class for the batch data entry, supports all the custom settings you might have.
*/
@isTest
private class BDE_BatchEntry_TEST {

    @IsTest
    private static void shouldGetBatchDataEntrySettings () {
        Batch_Data_Entry_Settings__c settings = BDE_BatchEntry_CTRL.getBatchDataEntrySettings();
        System.assertNotEquals(settings, null, 'Batch Data Entry Setting should not be null');
    }

    @IsTest
    private static void shouldUpsertRetirementAlert () {
        BDE_BatchEntry_CTRL.upsertRetirementAlert(true);
        Batch_Data_Entry_Settings__c settings = Batch_Data_Entry_Settings__c.getValues(UserInfo.getUserId());
        System.assertEquals(settings.Viewed_Retirement_Alert__c, true, 'The retirement alert should be checked');
    }
}