src/objects/Data_Import_Field_Mapping__mdt.object
<CustomObject>
    <description>Used for Data Import Advanced Mapping definitions. These are mappings of source fields on the NPSP Data Import object to target fields on standard or custom objects.</description>
    <fields>
        <fullName>Data_Import_Field_Mapping_Set__c</fullName>
        <description>The Data Import Field Mapping Set containing this field mapping.</description>
        <inlineHelpText>The Data Import Field Mapping Set containing this field mapping.</inlineHelpText>
        <label>Data Import Field Mapping Set</label>
        <referenceTo>Data_Import_Field_Mapping_Set__mdt</referenceTo>
        <relationshipLabel>Data Import Field Mappings</relationshipLabel>
        <relationshipName>Data_Import_Field_Mappings</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <description>When checked, indicates this record was deleted from the Data Import Advanced Mapping user interface and will be ignored during NPSP Data Import processing.</description>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When checked, indicates this record was deleted from the Data Import Advanced Mapping user interface and will be ignored during NPSP Data Import processing.</inlineHelpText>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <description>Indicates if the field on the NPSP Data Import object must contain a value. When it's required, Dry Run will fail if that field doesn't contain a value.</description>
        <inlineHelpText>Indicates if the field on the NPSP Data Import object must contain a value. When it's required, Dry Run will fail if that field doesn't contain a value.</inlineHelpText>
        <label>Required?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Field_API_Name__c</fullName>
        <description>The API name of the field on the NPSP Data Import object.</description>
        <inlineHelpText>The API name of the field on the NPSP Data Import object.</inlineHelpText>
        <label>Source Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Field_API_Name__c</fullName>
        <description>The API name of the field on the target object.</description>
        <inlineHelpText>The API name of the field on the target object.</inlineHelpText>
        <label>Target Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Object_Mapping__c</fullName>
        <description>The target Object Group for this Field Mapping.</description>
        <inlineHelpText>The target Data Import Object Group for this field mapping.</inlineHelpText>
        <label>Target Object Mapping</label>
        <referenceTo>Data_Import_Object_Mapping__mdt</referenceTo>
        <relationshipLabel>Data Import Field Mappings</relationshipLabel>
        <relationshipName>Data_Import_Field_Mappings</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <label>Data Import Field Mapping</label>
    <pluralLabel>Data Import Field Mappings</pluralLabel>
</CustomObject>

src/objects/Data_Import_Field_Mapping_Set__mdt.object
<CustomObject>
    <description>Used for Data Import Advanced Mapping definitions. These are collections of Data Import Field Mappings.</description>
    <fields>
        <fullName>Data_Import_Object_Mapping_Set__c</fullName>
        <description>The Data Import Object Group that contains this Field Mapping Set.</description>
        <inlineHelpText>The Data Import Object Group that contains this Field Mapping Set.</inlineHelpText>
        <label>Data Import Object Mapping Set</label>
        <referenceTo>Data_Import_Object_Mapping_Set__mdt</referenceTo>
        <relationshipLabel>Data Import Field Mapping Sets</relationshipLabel>
        <relationshipName>Data_Import_Field_Mapping_Sets</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <label>Data Import Field Mapping Set</label>
    <pluralLabel>Data Import Field Mapping Sets</pluralLabel>
</CustomObject>

src/objects/Data_Import_Object_Mapping__mdt.object
<CustomObject>
    <description>Used for Data Import Advanced Mapping definitions. These represent Object Groups and their relationships which will be used for different NPSP Data Import batches.</description>
    <fields>
        <fullName>Custom_Mapping_Logic_Class__c</fullName>
        <description>If custom apex logic should be used to map the fields for this object, then this field should be populated with the name of a class (including namespace if needed) that extends the BDI_ObjectMappingLogic class and overrides the populateObject method.</description>
        <inlineHelpText>If custom apex logic should be used to map the fields for this object, then this field should be populated with the name of a class (including namespace if needed) that extends the BDI_ObjectMappingLogic class and overrides the populateObject method.</inlineHelpText>
        <label>Custom Mapping Logic Class</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Import_Object_Mapping_Set__c</fullName>
        <description>The Data Import Object Group containing this record.</description>
        <inlineHelpText>The Data Import Object Group containing this record.</inlineHelpText>
        <label>Data Import Object Mapping Set</label>
        <referenceTo>Data_Import_Object_Mapping_Set__mdt</referenceTo>
        <relationshipLabel>Data Import Object Mappings</relationshipLabel>
        <relationshipName>Data_Import_Object_Mappings</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Imported_Record_Field_Name__c</fullName>
        <description>The Field API Name on the NPSP Data Import object where the ID for the imported record will be placed when the import is successful. This is also where the code will verify if this record was imported or matched.</description>
        <inlineHelpText>The Field API Name on the NPSP Data Import object where the ID for the imported record will be placed when the import is successful. This is also where the code will verify if this record was imported or matched.</inlineHelpText>
        <label>Imported Record Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Imported_Record_Status_Field_Name__c</fullName>
        <description>The Field API Name where the success or failure of the import will be recorded for an NPSP Data Import record.</description>
        <inlineHelpText>The Field API Name where the success or failure of the import will be recorded for an NPSP Data Import record.</inlineHelpText>
        <label>Imported Record Status Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <description>The API name for the target object for this Object Group.</description>
        <inlineHelpText>The API name for the target object for this Object Group.</inlineHelpText>
        <label>Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Data_Import_Object_Name__c</fullName>
        <description>The legacy Data Import object name of the object this Data Import Object Group is based on.</description>
        <inlineHelpText>The legacy Data Import object name of the object this Data Import Object Group is based on.</inlineHelpText>
        <label>Legacy Data Import Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Predecessor__c</fullName>
        <description>The Data Import Object Group record that must exist before this record can be created (either Parent or Child).</description>
        <inlineHelpText>The Data Import Object Group record that must exist before this record can be created (either Parent or Child).</inlineHelpText>
        <label>Predecessor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_Field__c</fullName>
        <description>If this Object Group is a child of the predecessor, this field should look up to the parent. If it's the parent of the predecessor, this should be the lookup field on the child record.</description>
        <inlineHelpText>If this Object Group is a child of the predecessor, this field should look up to the parent. If it's the parent of the predecessor, this should be the lookup field on the child record.</inlineHelpText>
        <label>Relationship Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_To_Predecessor__c</fullName>
        <description>This indicates if this object is a parent or child of the predecessor.</description>
        <inlineHelpText>This indicates if this object is a parent or child of the predecessor.</inlineHelpText>
        <label>Relationship To Predecessor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Parent</fullName>
                    <default>true</default>
                    <label>Parent</label>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>No Predecessor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Import Object Mapping</label>
    <pluralLabel>Data Import Object Mappings</pluralLabel>
</CustomObject>

src/objects/Data_Import_Object_Mapping_Set__mdt.object
<CustomObject>
    <description>Used for Data Import Advanced Mapping definitions. These are collections of Data Import Object Groups.</description>
    <label>Data Import Object Mapping Set</label>
    <pluralLabel>Data Import Object Mapping Sets</pluralLabel>
</CustomObject>

src/objects/Data_Import_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Data Import Settings</label>
</CustomObject>

force-app/main/default/objects/Data_Import_Settings__c/fields/Default_Data_Import_Field_Mapping_Set__c.field-meta.xml
<CustomField>
    <fullName>Default_Data_Import_Field_Mapping_Set__c</fullName>
    <description>The custom metadata api name of the Data Import Field Mapping Set record that should be used by default.</description>
    <inlineHelpText>The custom metadata api name of the Data Import Field Mapping Set record that should be used by default.</inlineHelpText>
    <label>Default Data Import Field Mapping Set</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/objects/DataImport__c.object
<CustomObject>
    <description>Custom object to hold denormalized data records that can be imported into the Nonprofit Success Pack.</description>
    <fields>
        <fullName>Donation_Amount__c</fullName>
        <inlineHelpText>Opportunity.Amount</inlineHelpText>
        <label>Donation Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>NPSP Data Import</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Data Import ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPSP Data Imports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BDI_MappingServiceAdvanced.cls
/*
    Copyright (c) 2019 Salesforce.org
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Salesforce.org
* @date 2019
* @group Batch Data Import
* @group-content ../../ApexDocContent/BatchDataImport.htm
* @description Implement field mapping behavior for mapping with custom metadata types
*/

public with sharing class BDI_MappingServiceAdvanced implements BDI_MappingService {

    public class MappingServiceException extends Exception{}

    public static final String DEFAULT_DATA_IMPORT_FIELD_MAPPING_SET_NAME = 'Default_Field_Mapping_Set';

    public Data_Import_Field_Mapping_Set__mdt diFieldMappingSet;
    public String fieldMappingSetName;

    public Map<String,BDI_ObjectMapping> objectMappingByDevName = new Map<String,BDI_ObjectMapping>();
    public Map<String,BDI_FieldMapping> fieldMappingByDevName = new Map<String,BDI_FieldMapping>();
    public Map<String,BDI_FieldMapping> fieldMappingByTargetFieldName = new Map<String,BDI_FieldMapping>();
    public Map<String,BDI_FieldMapping[]> fieldMappingsByObjMappingDevName = new Map<String,BDI_FieldMapping[]>();
    public Map<String,BDI_FieldMapping[]> fieldMappingsByObjMappingLegacyName = new Map<String,BDI_FieldMapping[]>();
    public Set<String> importedRecordFieldNames = new Set<String>();

    public BDI_FieldMappingSet fieldMappingSet;

    private static BDI_MappingServiceAdvanced fieldMappingInstance = null;

    /**
    * @description Reads Data_Import_Field_Mapping__mdt field mappings and produces a map of source field
    * to target field wrappers.
    */
    public Map<SObjectField, BDI_TargetFields> getTargetFieldsBySourceField() {

        Map<SObjectField, BDI_TargetFields> targetFieldsBySourceField =
                new Map<SObjectField, BDI_TargetFields>();

        String sourceObject = DataImport__c.SObjectType.getDescribe().getName();
        for (String dataImportObjectName : fieldMappingsByObjMappingDevName.keySet()) {

            String targetObject =
                    objectMappingByDevName.get(dataImportObjectName).Object_API_Name;
            List<BDI_FieldMapping> fieldMappingsForThisDataImportObject =
                    fieldMappingsByObjMappingDevName.get(dataImportObjectName);

            for (BDI_FieldMapping dataImportFieldMapping :
                    fieldMappingsForThisDataImportObject) {

                String sourceField = dataImportFieldMapping.Source_Field_API_Name;

                SObjectField sourceSObjectField =
                        UTIL_Describe.getFieldDescribe(
                                sourceObject, sourceField).getSobjectField();

                String targetField = dataImportFieldMapping.Target_Field_API_Name;

                if (targetFieldsBySourceField.keySet().contains(sourceSObjectField)) {
                    targetFieldsBySourceField.get(
                            sourceSObjectField).addTargetField(targetObject, targetField);
                } else {
                    BDI_TargetFields targetFields = new BDI_TargetFields();
                    targetFields.addTargetField(targetObject, targetField);
                    targetFieldsBySourceField.put(sourceSObjectField, targetFields);
                }
            }
        }
        return targetFieldsBySourceField;
    }

    /*******************************************************************************************************
    * @description return singleton instance of the class
    */
    public static BDI_MappingServiceAdvanced getInstance() {
        if (fieldMappingInstance == null) {
            fieldMappingInstance = new BDI_MappingServiceAdvanced();
            fieldMappingInstance.setFieldMappingSetName(null);
            fieldMappingInstance.retrieveCustMetadata();
        }
        return fieldMappingInstance;
    }

    /*******************************************************************************************************
    * @description return singleton instance of the class using specified field mapping set dev name
    */
    public static BDI_MappingServiceAdvanced getInstance(String fieldMappingSetDevName) {

        if (fieldMappingInstance == null) {
            fieldMappingInstance = new BDI_MappingServiceAdvanced();
            fieldMappingInstance.setFieldMappingSetName(fieldMappingSetDevName);
            fieldMappingInstance.retrieveCustMetadata();
        } else if(fieldMappingInstance.diFieldMappingSet.DeveloperName != fieldMappingSetDevName) {
            throw new MappingServiceException('Error: Field Mapping Set may not be changed after '+ 
                                                'initial instantiation');
        }
        return fieldMappingInstance;
    }

    /**
    * @description Sets instance member variable holding instance of this class.  Primarily
    * used to facilitate dependency injection in tests.
    * @param bdiFieldMappingInstance An instance of the BDI_MappingServiceAdvanced class.
    */
    @TestVisible
    private static void setInstance(BDI_MappingServiceAdvanced bdiFieldMappingInstance){
        fieldMappingInstance = bdiFieldMappingInstance;
    }

    /*******************************************************************************************************
    * @description For the provided fields (in the form DIObject.developerfieldname) and target object, 
    * return a map of DI field (key) to mapped field name on the destination record (value). 
    *
    * @param dataImportObjectName the bdi object we care about (Contact1, Contact2, Account1, etc)
    * @param targetObjectName the underlying object the bdi object is (ie, Contact, Account, etc)
    * @param dataImportFields the DataImport fields to consider
    * @return Map<String, String> a map of DataImport fields to underlying object fields (eg, Donation_Amount__c => Amount)
    *
    */

    public Map<String,String> getFieldMap(String dataImportObjectName, 
                                            String targetObjectName, 
                                            List<String> dataImportFields) {

        Map<String,String> targetFieldByDataImportField = new Map<String,String>();

        BDI_FieldMapping[] fieldMappings = fieldMappingsByObjMappingLegacyName.get(dataImportObjectName);

        if (fieldMappings != null) {
            for (BDI_FieldMapping fieldMapping : fieldMappings) {
                targetFieldByDataImportField.put(
                    fieldMapping.Source_Field_API_Name.toLowerCase(),
                    fieldMapping.Target_Field_API_Name);
            }
        }

        return targetFieldByDataImportField;
    }

    private void setFieldMappingSetName(String fieldMappingSetDevName){
        if (fieldMappingSetDevName != null) {
            fieldMappingSetName = fieldMappingSetDevName;
        } else if (fieldMappingSetName == null) {
            //Retreive the Data Import Settings to determine the default field mapping set.
            Data_Import_Settings__c dis = UTIL_CustomSettingsFacade.getDataImportSettings();

            fieldMappingSetName = UTIL_Namespace.alignSchemaNSWithEnvironment(dis.Default_Data_Import_Field_Mapping_Set__c);
        }
    }

    private void retrieveCustMetadata(){
        //If the code is not in the npsp namespace, then the npsp field prefixes will need to be systematically removed.
        Map<String,Data_Import_Object_Mapping__mdt> objMappingsByDevName =
            new Map<String,Data_Import_Object_Mapping__mdt>();

        diFieldMappingSet = [SELECT id, 
                                MasterLabel, 
                                DeveloperName, 
                                Data_Import_Object_Mapping_Set__c,
                                Data_Import_Object_Mapping_Set__r.DeveloperName    
                    FROM Data_Import_Field_Mapping_Set__mdt
                    WHERE DeveloperName =: fieldMappingSetName LIMIT 1];

        Data_Import_Field_Mapping__mdt[] fieldMappings = new List<Data_Import_Field_Mapping__mdt>();

        for (Data_Import_Object_Mapping__mdt diom:[SELECT Id,
                                            MasterLabel,
                                            Custom_Mapping_Logic_Class__c,
                                            DeveloperName, 
                                            Data_Import_Object_Mapping_Set__c,
                                            Data_Import_Object_Mapping_Set__r.DeveloperName, 
                                            Imported_Record_Field_Name__c,
                                            Imported_Record_Status_Field_Name__c,
                                            Is_Deleted__c,
                                            NamespacePrefix,
                                            Object_API_Name__c,
                                            Predecessor__c,
                                            Relationship_Field__c,
                                            Relationship_To_Predecessor__c,
                                            (SELECT MasterLabel,
                                                DeveloperName,
                                                Data_Import_Field_Mapping_Set__c,
                                                Data_Import_Field_Mapping_Set__r.DeveloperName,
                                                Required__c,
                                                Source_Field_API_Name__c,
                                                Target_Field_API_Name__c,
                                                Target_Object_Mapping__c,
                                                Target_Object_Mapping__r.DeveloperName,
                                                Target_Object_Mapping__r.Object_API_Name__c,
                                                Target_Object_Mapping__r.Legacy_Data_Import_Object_Name__c,
                                                Is_Deleted__c
                                            FROM Data_Import_Field_Mappings__r
                                            WHERE Is_Deleted__c = false
                                                AND Target_Object_Mapping__r.Is_Deleted__c = false)
                                    FROM Data_Import_Object_Mapping__mdt
                                    WHERE Data_Import_Object_Mapping_Set__c =: diFieldMappingSet.Data_Import_Object_Mapping_Set__c
                                        AND Is_Deleted__c = false
                                    ORDER BY MasterLabel ASC]) {

            if (diom.Data_Import_Field_Mappings__r != null &&
                diom.Data_Import_Field_Mappings__r.size() > 0) {

                fieldMappings.addAll(diom.Data_Import_Field_Mappings__r);
            }

            if (diom.Imported_Record_Field_Name__c != null) {
                if (UTIL_Namespace.shouldAlignNamespace) {
                    diom.Imported_Record_Field_Name__c = 
                        UTIL_Namespace.alignSchemaNSWithEnvironment(diom.Imported_Record_Field_Name__c);
                }
                
                importedRecordFieldNames.add(diom.Imported_Record_Field_Name__c.toLowerCase());
            }
            
            BDI_ObjectMapping objectMapping = new BDI_ObjectMapping(diom);
            this.objectMappingByDevName.put(objectMapping.DeveloperName,objectMapping);
        }


        if (fieldMappings != null) {
            for (Data_Import_Field_Mapping__mdt difm : fieldMappings) {

                BDI_FieldMapping fieldMapping = new BDI_FieldMapping(difm);

                BDI_FieldMapping[] tempFieldMappings = new BDI_FieldMapping[]{};

                if (fieldMappingsByObjMappingDevName.get(fieldMapping.Target_Object_Mapping_Dev_Name) != null) {
                    tempFieldMappings = fieldMappingsByObjMappingDevName.get(fieldMapping.Target_Object_Mapping_Dev_Name);
                }

                tempFieldMappings.add(fieldMapping);
                fieldMappingByDevName.put(fieldMapping.DeveloperName,fieldMapping);
                String objectAndField = fieldMapping.Target_Object_API_Name + '.' + fieldMapping.Target_Field_API_Name;
                fieldMappingByTargetFieldName.put(objectAndField,fieldMapping);
                fieldMappingsByObjMappingDevName.put(fieldMapping.Target_Object_Mapping_Dev_Name,tempFieldMappings);
                fieldMappingsByObjMappingLegacyName.put(
                    difm.Target_Object_Mapping__r.Legacy_Data_Import_Object_Name__c,
                    tempFieldMappings);
            }
        }

        fieldMappingSet = new BDI_FieldMappingSet(diFieldMappingSet,
            objectMappingByDevName,
            fieldMappingByDevName,
            fieldMappingByTargetFieldName,
            fieldMappingsByObjMappingDevName);
    }

    /*******************************************************************************************************
    * @description Method instantiates an instance of BDI_MappingServiceAdvanced by a given field mapping
    * set name and returns an instance of BDI_FieldMappingSet.
    *
    * @param fieldMappingSetName: Developer name of a Data_Import_Field_Mapping_Set__mdt record.
    *
    * @return fieldMappingSet: Instance of BDI_FieldMappingSet.
    */
    @AuraEnabled
    public static BDI_FieldMappingSet getFieldMappingSet(String fieldMappingSetName) {
        getInstance(fieldMappingSetName);
        return fieldMappingInstance.fieldMappingSet;
    }
}