src/objects/DataImport__c.object
<CustomObject>
    <description>Custom object to hold denormalized data records that can be imported into the Nonprofit Success Pack.</description>
    <fields>
        <fullName>Donation_Amount__c</fullName>
        <inlineHelpText>Opportunity.Amount</inlineHelpText>
        <label>Donation Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Donation_Date__c</fullName>
        <inlineHelpText>Opportunity.CloseDate</inlineHelpText>
        <label>Donation Date</label>
        <type>Date</type>
    </fields>
    <label>NPSP Data Import</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Data Import ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPSP Data Imports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GiftBatchView_TEST.cls
@IsTest
private class GiftBatchView_TEST {

    @IsTest
    static void sample_gift_batch_view() {
        Gifts gifts = dummyGifts();
        GiftBatch giftBatch = new GiftBatch(gifts);
        GiftBatchView giftBatchView =
                new GiftBatchView(new GiftBatchDTO(giftBatch));
        System.debug(LoggingLevel.ERROR, '*** variable value: ' +
                JSON.serializePretty(giftBatchView));
        System.debug(LoggingLevel.ERROR, '^^^^^^ giftBatchView ^^^^^^');
    }

    private static Gifts dummyGifts() {
        return new Gifts(
                new List<DataImport__c>{
                        new DataImport__c(
                                Donation_Amount__c = 100,
                                Donation_Date__c = Date.today()
                        ),
                        new DataImport__c(
                                Donation_Amount__c = 100,
                                Donation_Date__c = Date.today()
                        )
                }
        );
    }
}