src/objects/Data_Import_Field_Mapping__mdt.object
<CustomObject>
    <description>Used for Data Import Advanced Mapping definitions. These are mappings of source fields on the NPSP Data Import object to target fields on standard or custom objects.</description>
    <fields>
        <fullName>Target_Field_API_Name__c</fullName>
        <description>The API name of the field on the target object.</description>
        <inlineHelpText>The API name of the field on the target object.</inlineHelpText>
        <label>Target Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Object_Mapping__c</fullName>
        <description>The target Object Group for this Field Mapping.</description>
        <inlineHelpText>The target Data Import Object Group for this field mapping.</inlineHelpText>
        <label>Target Object Mapping</label>
        <referenceTo>Data_Import_Object_Mapping__mdt</referenceTo>
        <relationshipLabel>Data Import Field Mappings</relationshipLabel>
        <relationshipName>Data_Import_Field_Mappings</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <label>Data Import Field Mapping</label>
    <pluralLabel>Data Import Field Mappings</pluralLabel>
</CustomObject>

src/objects/Data_Import_Object_Mapping__mdt.object
<CustomObject>
    <description>Used for Data Import Advanced Mapping definitions. These represent Object Groups and their relationships which will be used for different NPSP Data Import batches.</description>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <description>The API name for the target object for this Object Group.</description>
        <inlineHelpText>The API name for the target object for this Object Group.</inlineHelpText>
        <label>Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Data Import Object Mapping</label>
    <pluralLabel>Data Import Object Mappings</pluralLabel>
</CustomObject>

src/classes/FORM_MappingWrapper.cls
public with sharing class FORM_MappingWrapper {

    String targetObject; 
    public Data_Import_Field_Mapping__mdt fieldMapping;
    List<String> picklistValues;
    Integer doubleSpecifiedPrecision;



    public FORM_MappingWrapper(Data_Import_Field_Mapping__mdt fieldMapping) {
        this.fieldMapping = fieldMapping;
        targetObject = fieldMapping.Target_Object_Mapping__r.Object_API_Name__c;

        // Get the target object/field describe to see what type it is
        Schema.DescribeFieldResult fieldDescribeResult = UTIL_Describe.getFieldDescribe(targetObject, fieldMapping.Target_Field_API_Name__c);


        // Get the necessary values from the describe 
        

    }
}