src/objects/Data_Import_Field_Mapping__mdt.object
<CustomObject>
    <description>Used for Data Import Advanced Mapping definitions. These are mappings of source fields on the NPSP Data Import object to target fields on standard or custom objects.</description>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <description>When checked, indicates this record was deleted from the Data Import Advanced Mapping user interface and will be ignored during NPSP Data Import processing.</description>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When checked, indicates this record was deleted from the Data Import Advanced Mapping user interface and will be ignored during NPSP Data Import processing.</inlineHelpText>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Source_Field_API_Name__c</fullName>
        <description>The API name of the field on the NPSP Data Import object.</description>
        <inlineHelpText>The API name of the field on the NPSP Data Import object.</inlineHelpText>
        <label>Source Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Data Import Field Mapping</label>
    <pluralLabel>Data Import Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/classes/FieldMappings.cls
public with sharing class FieldMappings extends fflib_SObjects {

    public FieldMappings(List<Data_Import_Field_Mapping__mdt> records){
        super(records);
    }

    public List<Data_Import_Field_Mapping__mdt> getMappings() {
        List<Data_Import_Field_Mapping__mdt> dataImportFieldMappings = new List<Data_Import_Field_Mapping__mdt>();
        for (Data_Import_Field_Mapping__mdt dataImportFieldMapping : (List<Data_Import_Field_Mapping__mdt>) getRecords()) {
            if (!dataImportFieldMapping.Is_Deleted__c) {
                dataImportFieldMappings.add(dataImportFieldMapping);
            }
        }
        return dataImportFieldMappings;
    }

    public Map<String, List<Data_Import_Field_Mapping__mdt>> getMappingsByFieldApiName() {
        Map<String, List<Data_Import_Field_Mapping__mdt>> mappingsByField =
                new Map<String, List<Data_Import_Field_Mapping__mdt>>();
        for (Data_Import_Field_Mapping__mdt dataImportFieldMapping : getMappings()) {
            List<Data_Import_Field_Mapping__mdt> dataImportFieldMappings =
                    mappingsByField.get(dataImportFieldMapping.Source_Field_API_Name__c);
            if (null != dataImportFieldMappings) {
                dataImportFieldMappings.add(dataImportFieldMapping);
            } else {
                mappingsByField.put(dataImportFieldMapping.Source_Field_API_Name__c,
                        new List<Data_Import_Field_Mapping__mdt>{
                                dataImportFieldMapping
                        });
            }
        }
        return mappingsByField;
    }
}