src/objects/Data_Import_Field_Mapping__mdt.object
<CustomObject>
    <description>Used for Data Import Advanced Mapping definitions. These are mappings of source fields on the NPSP Data Import object to target fields on standard or custom objects.</description>
    <fields>
        <fullName>Data_Import_Field_Mapping_Set__c</fullName>
        <description>The Data Import Field Mapping Set containing this field mapping.</description>
        <inlineHelpText>The Data Import Field Mapping Set containing this field mapping.</inlineHelpText>
        <label>Data Import Field Mapping Set</label>
        <referenceTo>Data_Import_Field_Mapping_Set__mdt</referenceTo>
        <relationshipLabel>Data Import Field Mappings</relationshipLabel>
        <relationshipName>Data_Import_Field_Mappings</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <description>When checked, indicates this record was deleted from the Data Import Advanced Mapping user interface and will be ignored during NPSP Data Import processing.</description>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When checked, indicates this record was deleted from the Data Import Advanced Mapping user interface and will be ignored during NPSP Data Import processing.</inlineHelpText>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <description>Indicates if the field on the NPSP Data Import object must contain a value. When it's required, Dry Run will fail if that field doesn't contain a value.</description>
        <inlineHelpText>Indicates if the field on the NPSP Data Import object must contain a value. When it's required, Dry Run will fail if that field doesn't contain a value.</inlineHelpText>
        <label>Required?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Field_API_Name__c</fullName>
        <description>The API name of the field on the NPSP Data Import object.</description>
        <inlineHelpText>The API name of the field on the NPSP Data Import object.</inlineHelpText>
        <label>Source Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Field_API_Name__c</fullName>
        <description>The API name of the field on the target object.</description>
        <inlineHelpText>The API name of the field on the target object.</inlineHelpText>
        <label>Target Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Object_Mapping__c</fullName>
        <description>The target Object Group for this Field Mapping.</description>
        <inlineHelpText>The target Data Import Object Group for this field mapping.</inlineHelpText>
        <label>Target Object Mapping</label>
        <referenceTo>Data_Import_Object_Mapping__mdt</referenceTo>
        <relationshipLabel>Data Import Field Mappings</relationshipLabel>
        <relationshipName>Data_Import_Field_Mappings</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <label>Data Import Field Mapping</label>
    <pluralLabel>Data Import Field Mappings</pluralLabel>
</CustomObject>

src/objects/Data_Import_Field_Mapping_Set__mdt.object
<CustomObject>
    <description>Used for Data Import Advanced Mapping definitions. These are collections of Data Import Field Mappings.</description>
    <label>Data Import Field Mapping Set</label>
    <pluralLabel>Data Import Field Mapping Sets</pluralLabel>
</CustomObject>

src/objects/Data_Import_Object_Mapping__mdt.object
<CustomObject>
    <description>Used for Data Import Advanced Mapping definitions. These represent Object Groups and their relationships which will be used for different NPSP Data Import batches.</description>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <description>The API name for the target object for this Object Group.</description>
        <inlineHelpText>The API name for the target object for this Object Group.</inlineHelpText>
        <label>Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Data Import Object Mapping</label>
    <pluralLabel>Data Import Object Mappings</pluralLabel>
</CustomObject>

src/objects/DataImport__c.object
<CustomObject>
    <description>Custom object to hold denormalized data records that can be imported into the Nonprofit Success Pack.</description>
    <label>NPSP Data Import</label>
    <nameField>
        <displayFormat>DI-{000000}</displayFormat>
        <label>Data Import ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPSP Data Imports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BDI_FieldMapping.cls
/*
    Copyright (c) 2019 Salesforce.org
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Salesforce.org
* @date 2019
* @group Batch Data Import
* @group-content ../../ApexDocContent/BatchDataImport.htm
* @description Wrapper class to hold data related to the field mapping 
*/
public with sharing class BDI_FieldMapping {
    @AuraEnabled public String DeveloperName;
    @AuraEnabled public String MasterLabel;
    @AuraEnabled public String Source_Field_Label;
    @AuraEnabled public String Source_Field_API_Name;
    @AuraEnabled public String Source_Field_Data_Type;
    @AuraEnabled public String Target_Field_Label;
    @AuraEnabled public String Target_Field_API_Name;
    @AuraEnabled public String Target_Field_Data_Type;
    @AuraEnabled public String Data_Import_Field_Mapping_Set;
    @AuraEnabled public String Target_Object_Mapping_Dev_Name;
    @AuraEnabled public String Required;
    @AuraEnabled public Boolean Is_Deleted;
    @AuraEnabled public String Source_Field_Display_Type_Label;
    @AuraEnabled public String Target_Field_Display_Type_Label;

    public BDI_FieldMapping(Data_Import_Field_Mapping__mdt fieldMapping) {
        String dataImport = SobjectType.DataImport__c.Name;
        String objectAPIName = fieldMapping.Target_Object_Mapping__r.Object_API_Name__c;
        String sourceFieldAPIName = fieldMapping.Source_Field_API_Name__c;
        String targetFieldAPIName = fieldMapping.Target_Field_API_Name__c;

        Schema.DescribeFieldResult sourceFieldDescribe = UTIL_Describe.getFieldDescribe(
            dataImport,
            sourceFieldAPIName);

        Schema.DescribeFieldResult targetFieldDescribe = UTIL_Describe.getFieldDescribe(
            objectAPIName,
            targetFieldAPIName);

        this.DeveloperName = fieldMapping.DeveloperName;
        this.MasterLabel = fieldMapping.MasterLabel;

        this.Source_Field_Label = sourceFieldDescribe.label;
        this.Source_Field_API_Name = fieldMapping.Source_Field_API_Name__c;
        this.Source_Field_Data_Type = String.valueOf(sourceFieldDescribe.type);
        this.Source_Field_Display_Type_Label = UTIL_Describe.LABELS_BY_DISPLAY_TYPE.get(this.Source_Field_Data_Type);

        this.Target_Field_Label = targetFieldDescribe.label;
        this.Target_Field_API_Name = fieldMapping.Target_Field_API_Name__c;
        this.Target_Field_Data_Type = String.valueOf(targetFieldDescribe.type);
        this.Target_Field_Display_Type_Label = UTIL_Describe.LABELS_BY_DISPLAY_TYPE.get(this.Target_Field_Data_Type);

        this.Data_Import_Field_Mapping_Set = fieldMapping.Data_Import_Field_Mapping_Set__r.DeveloperName;
        this.Target_Object_Mapping_Dev_Name = fieldMapping.Target_Object_Mapping__r.DeveloperName;
        this.Required = fieldMapping.Required__c;
        this.Is_Deleted = fieldMapping.Is_Deleted__c;
    }
}