src/objects/Data_Import_Field_Mapping__mdt.object
<CustomObject>
    <description>Used for Data Import Advanced Mapping definitions. These are mappings of source fields on the NPSP Data Import object to target fields on standard or custom objects.</description>
    <fields>
        <fullName>Data_Import_Field_Mapping_Set__c</fullName>
        <description>The Data Import Field Mapping Set containing this field mapping.</description>
        <inlineHelpText>The Data Import Field Mapping Set containing this field mapping.</inlineHelpText>
        <label>Data Import Field Mapping Set</label>
        <referenceTo>Data_Import_Field_Mapping_Set__mdt</referenceTo>
        <relationshipLabel>Data Import Field Mappings</relationshipLabel>
        <relationshipName>Data_Import_Field_Mappings</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <description>When checked, indicates this record was deleted from the Data Import Advanced Mapping user interface and will be ignored during NPSP Data Import processing.</description>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When checked, indicates this record was deleted from the Data Import Advanced Mapping user interface and will be ignored during NPSP Data Import processing.</inlineHelpText>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <description>Indicates if the field on the NPSP Data Import object must contain a value. When it's required, Dry Run will fail if that field doesn't contain a value.</description>
        <inlineHelpText>Indicates if the field on the NPSP Data Import object must contain a value. When it's required, Dry Run will fail if that field doesn't contain a value.</inlineHelpText>
        <label>Required?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Field_API_Name__c</fullName>
        <description>The API name of the field on the NPSP Data Import object.</description>
        <inlineHelpText>The API name of the field on the NPSP Data Import object.</inlineHelpText>
        <label>Source Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Field_API_Name__c</fullName>
        <description>The API name of the field on the target object.</description>
        <inlineHelpText>The API name of the field on the target object.</inlineHelpText>
        <label>Target Field API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Object_Mapping__c</fullName>
        <description>The target Object Group for this Field Mapping.</description>
        <inlineHelpText>The target Data Import Object Group for this field mapping.</inlineHelpText>
        <label>Target Object Mapping</label>
        <referenceTo>Data_Import_Object_Mapping__mdt</referenceTo>
        <relationshipLabel>Data Import Field Mappings</relationshipLabel>
        <relationshipName>Data_Import_Field_Mappings</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <label>Data Import Field Mapping</label>
    <pluralLabel>Data Import Field Mappings</pluralLabel>
</CustomObject>

src/objects/Data_Import_Field_Mapping_Set__mdt.object
<CustomObject>
    <description>Used for Data Import Advanced Mapping definitions. These are collections of Data Import Field Mappings.</description>
    <fields>
        <fullName>Data_Import_Object_Mapping_Set__c</fullName>
        <description>The Data Import Object Group that contains this Field Mapping Set.</description>
        <inlineHelpText>The Data Import Object Group that contains this Field Mapping Set.</inlineHelpText>
        <label>Data Import Object Mapping Set</label>
        <referenceTo>Data_Import_Object_Mapping_Set__mdt</referenceTo>
        <relationshipLabel>Data Import Field Mapping Sets</relationshipLabel>
        <relationshipName>Data_Import_Field_Mapping_Sets</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <label>Data Import Field Mapping Set</label>
    <pluralLabel>Data Import Field Mapping Sets</pluralLabel>
</CustomObject>

src/objects/Data_Import_Object_Mapping__mdt.object
<CustomObject>
    <description>Used for Data Import Advanced Mapping definitions. These represent Object Groups and their relationships which will be used for different NPSP Data Import batches.</description>
    <fields>
        <fullName>Custom_Mapping_Logic_Class__c</fullName>
        <description>If custom apex logic should be used to map the fields for this object, then this field should be populated with the name of a class (including namespace if needed) that extends the BDI_ObjectMappingLogic class and overrides the populateObject method.</description>
        <inlineHelpText>If custom apex logic should be used to map the fields for this object, then this field should be populated with the name of a class (including namespace if needed) that extends the BDI_ObjectMappingLogic class and overrides the populateObject method.</inlineHelpText>
        <label>Custom Mapping Logic Class</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Import_Object_Mapping_Set__c</fullName>
        <description>The Data Import Object Group containing this record.</description>
        <inlineHelpText>The Data Import Object Group containing this record.</inlineHelpText>
        <label>Data Import Object Mapping Set</label>
        <referenceTo>Data_Import_Object_Mapping_Set__mdt</referenceTo>
        <relationshipLabel>Data Import Object Mappings</relationshipLabel>
        <relationshipName>Data_Import_Object_Mappings</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Imported_Record_Field_Name__c</fullName>
        <description>The Field API Name on the NPSP Data Import object where the ID for the imported record will be placed when the import is successful. This is also where the code will verify if this record was imported or matched.</description>
        <inlineHelpText>The Field API Name on the NPSP Data Import object where the ID for the imported record will be placed when the import is successful. This is also where the code will verify if this record was imported or matched.</inlineHelpText>
        <label>Imported Record Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Imported_Record_Status_Field_Name__c</fullName>
        <description>The Field API Name where the success or failure of the import will be recorded for an NPSP Data Import record.</description>
        <inlineHelpText>The Field API Name where the success or failure of the import will be recorded for an NPSP Data Import record.</inlineHelpText>
        <label>Imported Record Status Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <description>The API name for the target object for this Object Group.</description>
        <inlineHelpText>The API name for the target object for this Object Group.</inlineHelpText>
        <label>Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legacy_Data_Import_Object_Name__c</fullName>
        <description>The legacy Data Import object name of the object this Data Import Object Group is based on.</description>
        <inlineHelpText>The legacy Data Import object name of the object this Data Import Object Group is based on.</inlineHelpText>
        <label>Legacy Data Import Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Predecessor__c</fullName>
        <description>The Data Import Object Group record that must exist before this record can be created (either Parent or Child).</description>
        <inlineHelpText>The Data Import Object Group record that must exist before this record can be created (either Parent or Child).</inlineHelpText>
        <label>Predecessor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_Field__c</fullName>
        <description>If this Object Group is a child of the predecessor, this field should look up to the parent. If it's the parent of the predecessor, this should be the lookup field on the child record.</description>
        <inlineHelpText>If this Object Group is a child of the predecessor, this field should look up to the parent. If it's the parent of the predecessor, this should be the lookup field on the child record.</inlineHelpText>
        <label>Relationship Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_To_Predecessor__c</fullName>
        <description>This indicates if this object is a parent or child of the predecessor.</description>
        <inlineHelpText>This indicates if this object is a parent or child of the predecessor.</inlineHelpText>
        <label>Relationship To Predecessor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Parent</fullName>
                    <default>true</default>
                    <label>Parent</label>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>No Predecessor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Data Import Object Mapping</label>
    <pluralLabel>Data Import Object Mappings</pluralLabel>
</CustomObject>

src/objects/Data_Import_Object_Mapping_Set__mdt.object
<CustomObject>
    <description>Used for Data Import Advanced Mapping definitions. These are collections of Data Import Object Groups.</description>
    <label>Data Import Object Mapping Set</label>
    <pluralLabel>Data Import Object Mapping Sets</pluralLabel>
</CustomObject>

src/classes/BDI_MigrationMappingHelper.cls
/*
    Copyright (c) 2019, Salesforce.org
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Salesforce.org
* @date 2019
* @group Batch Data Import
* @group-content ../../ApexDocContent/BatchDataImport.htm
* @description Helper class that supports BDI_MigrationMappingUtility and
* enables mocking of test data.
*/
public class BDI_MigrationMappingHelper {

    /*******************************************************************************************************
    * @description Get a list of by Data Import Object Mapping Set by Developer Name
    *
    * @param developerName: String name of the Data Import Object Mapping Set
    * @return List<Data_Import_Object_Mapping_Set__mdt>
    */
    public List<Data_Import_Object_Mapping_Set__mdt> getObjectMappingSet(String developerName) {
        List<Data_Import_Object_Mapping_Set__mdt> sets =
            [SELECT Id FROM Data_Import_Object_Mapping_Set__mdt WHERE DeveloperName = :developerName];
        return sets;
    }

    /*******************************************************************************************************
    * @description Get a list of by Data Import Field Mapping Set by Developer Name
    *
    * @param developerName: String name of the Data Import Field Mapping Set
    * @return List<Data_Import_Field_Mapping_Set__mdt>
    */
    public List<Data_Import_Field_Mapping_Set__mdt> getFieldMappingSet(String developerName) {
        List<Data_Import_Field_Mapping_Set__mdt> sets =
            [SELECT Id FROM Data_Import_Field_Mapping_Set__mdt WHERE DeveloperName = :developerName];
        return sets;
    }

    /*******************************************************************************************************
    * @description Get a list of Help Text Field Mappings from Data Import Help Text Field Describes
    *
    * @return List<Data_Import_Field_Mapping_Set__mdt>
    */
    public List<BDI_MigrationMappingUtility.HelpTextFieldMapping> getAllHelpTextFieldMappings() {

        Map<String, Schema.DescribeFieldResult> describeFieldResultsByFieldName =
            UTIL_Describe.getAllFieldsDescribe(UTIL_Namespace.StrAllNSPrefix(
                BDI_MigrationMappingUtility.DATA_IMPORT_OBJECT_NAME));

        List<BDI_MigrationMappingUtility.HelpTextFieldMapping> helpTextFieldMappings =
            new List<BDI_MigrationMappingUtility.HelpTextFieldMapping>();

        for (String dataImportFieldName : describeFieldResultsByFieldName.keySet()) {

            DescribeFieldResult sourceField = describeFieldResultsByFieldName.get(dataImportFieldName);
            BDI_MigrationMappingUtility.HelpTextFieldMapping helpTextFieldMapping =
                new BDI_MigrationMappingUtility.HelpTextFieldMapping(sourceField);

            helpTextFieldMappings.add(helpTextFieldMapping);
        }

        return helpTextFieldMappings;
    }

    /*******************************************************************************************************
     * @description Queries for default Object Mappings and builds a map of DeveloperName to Object Mapping
     * record used to check for existance of Object Mapping record without loop
     *
     * @param objectMappingSetId Id of the default Object Mapping Set
     * @return Collection of Object Mapping DeveloperName to Object Mapping record
     */
    public Map<String, Data_Import_Object_Mapping__mdt> getObjectMappingsBySetDeveloperName(String developerName) {

        Data_Import_Object_Mapping_Set__mdt[] objectMappingSets = [SELECT Id
            FROM Data_Import_Object_Mapping_Set__mdt
            WHERE DeveloperName = :developerName];

        Map<String, Data_Import_Object_Mapping__mdt> objectMappingsByDeveloperName =
            new Map<String, Data_Import_Object_Mapping__mdt>();

        if (objectMappingSets == null || objectMappingSets.size() == 0) {
            return objectMappingsByDeveloperName;
        }

        List<Data_Import_Object_Mapping__mdt> existingObjectMappings = [SELECT 
                    Id, 
                    Label, 
                    DeveloperName, 
                    Imported_Record_Field_Name__c,
                    Imported_Record_Status_Field_Name__c, 
                    Object_API_Name__c, 
                    Predecessor__c,
                    Relationship_Field__c, 
                    Relationship_To_Predecessor__c, 
                    Is_Deleted__c,
                    Legacy_Data_Import_Object_Name__c,
                    Custom_Mapping_Logic_Class__c
            FROM Data_Import_Object_Mapping__mdt
            WHERE Data_Import_Object_Mapping_Set__c = :objectMappingSets[0].Id
                AND Is_Deleted__c = false];

        for (Data_Import_Object_Mapping__mdt objectMapping : existingObjectMappings) {
            objectMappingsByDeveloperName.put(objectMapping.Legacy_Data_Import_Object_Name__c, objectMapping);
        }

        return objectMappingsByDeveloperName;
    }

    /*******************************************************************************************************
     * @description Queries for default Field Mappings and builds a map of DeveloperName to Field Mapping record
     * Used to check for existance of Field Mapping record without loop
     * @param fieldMappingSetId Id of the default Field Mapping Set
     * @return Collection of Field Mapping DeveloperName to Field Mapping record
     */
    public Map<String, Data_Import_Field_Mapping__mdt> getFieldMappingsByFieldMappingSetDeveloperName(
        String developerName) {

        Data_Import_Field_Mapping_Set__mdt[] fieldMappingSets = [SELECT Id
            FROM Data_Import_Field_Mapping_Set__mdt
            WHERE DeveloperName = :developerName];

        Map<String, Data_Import_Field_Mapping__mdt> fieldMappingsBySourceFieldName =
            new Map<String, Data_Import_Field_Mapping__mdt>();

        if (fieldMappingSets == null || fieldMappingSets.size() == 0) {
            return fieldMappingsBySourceFieldName;
        }

        List<Data_Import_Field_Mapping__mdt> existingFieldMappings = [SELECT 
                    Id, 
                    Label, 
                    MasterLabel,
                    DeveloperName, 
                    Data_Import_Field_Mapping_Set__c,
                    Data_Import_Field_Mapping_Set__r.Label,
                    Data_Import_Field_Mapping_Set__r.DeveloperName,
                    Required__c, 
                    Source_Field_API_Name__c, 
                    Target_Field_API_Name__c, 
                    Target_Object_Mapping__c,
                    Target_Object_Mapping__r.Object_API_Name__c,
                    Target_Object_Mapping__r.DeveloperName,
                    Target_OBject_Mapping__r.Legacy_Data_Import_Object_Name__c,
                    Target_Object_Mapping__r.MasterLabel,
                    Is_Deleted__c
            FROM Data_Import_Field_Mapping__mdt
            WHERE Data_Import_Field_Mapping_Set__c = :fieldMappingSets[0].Id
                AND Is_Deleted__c = false];

        String namespace = UTIL_Namespace.getNamespace();

        for (Data_Import_Field_Mapping__mdt fieldMapping : existingFieldMappings) {
            if (namespace != 'npsp') {
                fieldMapping.Source_Field_API_Name__c =
                    UTIL_Namespace.removeNSPrefixNpspOnly(fieldMapping.Source_Field_API_Name__c);
                fieldMapping.Target_Object_Mapping__r.Object_API_Name__c =
                    UTIL_Namespace.removeNSPrefixNpspOnly(fieldMapping.Target_Object_Mapping__r.Object_API_Name__c);
            }
            fieldMappingsBySourceFieldName.put(
                fieldMapping.Target_Object_Mapping__r.Object_API_Name__c
                + '.'
                + fieldMapping.Target_Object_Mapping__r.Legacy_Data_Import_Object_Name__c
                + '.'
                + fieldMapping.Source_Field_API_Name__c,
                fieldMapping);
        }

        return fieldMappingsBySourceFieldName;
    }
}