src/objects/Filter_Group__mdt.object
<CustomObject>
    <description>Filter Group header</description>
    <label>Filter Group</label>
    <pluralLabel>Filter Groups</pluralLabel>
</CustomObject>

src/objects/Rollup__mdt.object
<CustomObject>
    <description>NPSP Customizable Rollup definitions</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Filter_Group__c</fullName>
        <label>Filter Group</label>
        <referenceTo>Filter_Group__mdt</referenceTo>
        <relationshipLabel>Rollups</relationshipLabel>
        <relationshipName>Rollups</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Count</fullName>
                    <default>true</default>
                    <label>Count</label>
                </value>
                <value>
                    <fullName>Sum</fullName>
                </value>
                <value>
                    <fullName>Average</fullName>
                </value>
                <value>
                    <fullName>Largest</fullName>
                </value>
                <value>
                    <fullName>Smallest</fullName>
                </value>
                <value>
                    <fullName>First</fullName>
                </value>
                <value>
                    <fullName>Last</fullName>
                </value>
                <value>
                    <fullName>Years_Donated</fullName>
                    <label>Years Donated</label>
                </value>
                <value>
                    <fullName>Donor_Streak</fullName>
                    <label>Donor Streak</label>
                </value>
                <value>
                    <fullName>Best_Year</fullName>
                    <label>Best Year</label>
                </value>
                <value>
                    <fullName>Best_Year_Total</fullName>
                    <label>Best Year Total</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Summary_Field__c</fullName>
        <label>Target Field</label>
        <metadataRelationshipControllingField>Rollup__mdt.Summary_Object__c</metadataRelationshipControllingField>
        <referenceTo>FieldDefinition</referenceTo>
        <relationshipLabel>RollupsSummary</relationshipLabel>
        <relationshipName>RollupsSummary</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <label>Rollup</label>
    <pluralLabel>Rollups</pluralLabel>
</CustomObject>

src/classes/CRLP_RollupsUI_SVC.cls
/**
 * Created by randi.wilson on 12/27/17.
 */

public with sharing class CRLP_RollupsUI_SVC {


    public class TableItem{
        @AuraEnabled public String rollupType;
        @AuraEnabled public String rollupName;
        @AuraEnabled public String targetField;
        @AuraEnabled public String operation;
        @AuraEnabled public String filterGroupName;
        @AuraEnabled public String active;
    }

    public class RollupModel{
        @AuraEnabled public List<TableItem> items;
        //TODO: should the labels live in an enum or elsewhere to be easily accessible for other pages?
        @AuraEnabled public Map<String, String> labels = new Map<String,String>{
                'active' => Label.CRLP_Active,
                'cancel' => Label.stgBtnCancel,
                'clone' => Label.stgBtnClone,
                'delete' => Label.alloDeleteRow,
                'edit' => Label.stgBtnEdit,
                'filterCreate' => Label.CRLP_FilterCreate,
                'filterGroupName' => Label.CRLP_FilterGroupName,
                'filterGroupsTitle' => Label.CRLP_FilterGroups,
                'filterGroupsView' => Label.CRLP_FilterView,
                'filterNew' => Label.CRLP_FilterNew,
                'name' => Label.CRLP_Name,
                'operation' => Label.CRLP_Operation,
                'return' => Label.CRLP_Return,
                'rollupCreate' => Label.CRLP_RollupCreate,
                'rollupNew' => Label.CRLP_RollupNew,
                'rollupSummaryTitle' => Label.CRLP_RollupSummary,
                'rollupType' => Label.CRLP_RollupType,
                'save' => Label.stgBtnSave,
                'saveAndNew' => Label.lvlBtnSaveAndNew,
                'targetField' => Label.CRLP_TargetField
        };

    }

    @AuraEnabled
    public static RollupModel setupRollups() {
        RollupModel model = new RollupModel();

        model.items = getRollupDefinitions();

        return model;
    }

    @AuraEnabled
    public static List<TableItem> getRollupDefinitions(){
        List<TableItem> mdtTableList = new List<TableItem>();

        try{
            List<Rollup__mdt> mdtList = CRLP_Rollup_SEL.getRollupDefinitions();

            for(Integer i=0; i<mdtList.size(); i++){
                TableItem item = new TableItem();

                item.rollupType = 'TBD';
                item.rollupName = mdtList[i].MasterLabel;
                item.targetField = mdtList[i].Summary_Field__r.Label;
                item.filterGroupName = mdtList[i].Filter_Group__r.MasterLabel;
                item.operation = mdtList[i].Operation__c.replace('_', ' ');
                item.active = String.valueOf(mdtList[i].Active__c).capitalize();

                mdtTableList.add(item);
            }
        }

        catch(exception e){
            throw new AuraHandledException('Unable to load rollup information at this time. Error: '
            + e.getMessage());
        }

        return mdtTableList;

    }

}