src/objects/npe03__Recurring_Donation__c.object
<CustomObject>
    <fields>
        <fullName>ClosedReason__c</fullName>
        <description>The reason this Recurring Donation has its current Status value.</description>
        <inlineHelpText>The reason this Recurring Donation has its current Status value.</inlineHelpText>
        <label>Status Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Card Expired</fullName>
                </value>
                <value>
                    <fullName>Commitment Completed</fullName>
                </value>
                <value>
                    <fullName>Deceased Donor</fullName>
                </value>
                <value>
                    <fullName>Financial Difficulty</fullName>
                </value>
                <value>
                    <fullName>No Longer Interested</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>After this date, NPSP no longer creates installments for this Recurring Donation and updates Status to Closed.</description>
        <inlineHelpText>After this date, NPSP no longer creates installments for this Recurring Donation and updates Status to Closed.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The date that new or updated schedule information (Amount, Day of Month, etc.) for this Recurring Donation takes effect. The default is the current date.</description>
        <inlineHelpText>The date that new or updated schedule information (Amount, Day of Month, etc.) for this Recurring Donation takes effect. The default is the current date.</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/objects/RecurringDonationSchedule__c.object
<CustomObject>
    <description>Contains the current and past schedule(s) for each Recurring Donation. Records in this object are system maintained and should never be edited directly.</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>The ending date, if required, for this schedule record.</description>
        <inlineHelpText>The ending date, if required, for this schedule record.</inlineHelpText>
        <label>Schedule End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsPause__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set when the schedule record represents Recurring Donation pause date range</description>
        <inlineHelpText>Set when the schedule record represents Recurring Donation pause date range</inlineHelpText>
        <label>Is Pause</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StatusReason__c</fullName>
        <description>Contains additional details for the schedule. For example, it is a paused reason for a pause schedule.</description>
        <inlineHelpText>Contains additional details for the schedule. For example, it is a paused reason for a pause schedule.</inlineHelpText>
        <label>Status Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecurringDonation__c</fullName>
        <description>The Recurring Donation this schedule record is associated with.</description>
        <inlineHelpText>The Recurring Donation this schedule record is associated with.</inlineHelpText>
        <label>Recurring Donation</label>
        <referenceTo>npe03__Recurring_Donation__c</referenceTo>
        <relationshipLabel>Recurring Donation Schedules</relationshipLabel>
        <relationshipName>RecurringDonationSchedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The effective date for this schedule record.</description>
        <inlineHelpText>The effective date for this schedule record.</inlineHelpText>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Recurring Donation Schedule</label>
    <nameField>
        <displayFormat>RD-Schedule-{0000000000}</displayFormat>
        <label>Recurring Schedule Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recurring Donation Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RD2_PauseForm_CTRL.cls
/*
    Copyright (c) 2020, Salesforce.org
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Salesforce.org nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
* @author Salesforce.org
* @date 2020
* @group Recurring Donations
* @description Saves and retrieves pause details on a Recurring Donation record
*/
public with sharing class RD2_PauseForm_CTRL {

    /***
    * @description Recurring Donation Schedule service
    */
    @TestVisible
    private static RD2_ScheduleService scheduleService {
        get {
            if (scheduleService == null) {
                scheduleService = new RD2_ScheduleService();
            }
            return scheduleService;
        } set;
    }


    /**
     * @description 
     * @param 
     * @return void
     */
    @AuraEnabled
    public static void savePause(String jsonData) {
        try {
            PauseData data = (PauseData) JSON.deserialize(jsonData, PauseData.class);

            //deactivate current schedule(s)
            delete [
                SELECT Id FROM RecurringDonationSchedule__c 
                WHERE RecurringDonation__c = :data.recurringDonationId
                AND IsPause__c = true
            ];//TODO it should deactivate not delete

            //create new pause schedule
            RecurringDonationSchedule__c schedule = buildPauseSchedule(data);
            if (schedule.StartDate__c != null && schedule.EndDate__c != null) {
                insert schedule;
            }

        } catch(Exception e) {
            throwAuraHandledException(e.getMessage());
        }
    }

    /**
     * @description 
     * @param 
     * @return void
     */
    private static RecurringDonationSchedule__c buildPauseSchedule(PauseData data) {
        RecurringDonationSchedule__c schedule = new RecurringDonationSchedule__c(
            RecurringDonation__c = data.recurringDonationId,
            IsPause__c = true,
            StatusReason__c = data.pausedReason,
            StartDate__c = data.startDate,
            EndDate__c = data.resumeAfterDate
        );

        return schedule;
    }

    /**
     * @description Returns the Paused Reason value and label select options
     * @return String
     */
    @AuraEnabled(cacheable=false)
    public static String getPausedReason(Id recurringDonationId) {
        PausedReason reason = new PausedReason();
        reason.label = 'Paused Reason';//TODO //Schema.SObjectType.RecurringDonationSchedule__c.fields.StatusReason__c.getLabel();
        reason.options = getPausedReasonOptions();
        reason.placeholder = 'Select an Option';//TODO

        RecurringDonationSchedule__c schedule = scheduleService.getPauseSchedule(recurringDonationId);
        reason.value = schedule == null ? null : schedule.StatusReason__c;

        return JSON.serialize(reason);
    }

    /**
     * @description Returns the Paused Reason value and label select options
     * @return List<Option>
     */
    private static List<Option> getPausedReasonOptions() {
        List<Option> options = new List<Option>();
        List<Schema.PicklistEntry> entries = npe03__Recurring_Donation__c.ClosedReason__c.getDescribe().getPicklistValues();

        for (Schema.PicklistEntry entry : entries) {
            if (entry.isActive()) {                
                options.add(
                    new Option()
                        .withValue(entry.getValue())
                        .withLabel(entry.getLabel())
                );
            }
        }
        return options;
    }

    /***
    * @description Throws AuraHandledException
    * @param errMessage
    * @return void
    */
    private static void throwAuraHandledException(String errMessage) {
        AuraHandledException e = new AuraHandledException(errMessage);
        e.setMessage(errMessage);
        throw e;
    }

    /***
    * @description 
    */
    public class PauseData {
        public Id scheduleId;
        public Id recurringDonationId;
        public Date startDate;
        public Date resumeAfterDate;
        public String pausedReason;
    }

    /***
    * @description 
    */
    public class PausedReason {
        public String value;
        public String label;
        public List<Option> options;
        public String placeholder;
    }

    /**
     * @description Contains custom select option
     */
    public class Option {
        @AuraEnabled public String value;
        @AuraEnabled public String label;

        /**
         * @description Sets the option value
         * @param value The option value
         * @return Option This option instance
         */
        public Option withValue(String value) {
            this.value = value;
            return this;
        }

        /**
         * @description Sets the option label
         * @param label The option label
         * @return Option This option instance
         */
        public Option withLabel(String label) {
            this.label = label;
            return this;
        }
    }


}