src/objects/Opportunity.object
<CustomObject>
</CustomObject>

unpackaged/config/trial_tso/objects/Opportunity.object
    <recordTypes>
        <fullName>Donation</fullName>
        <active>true</active>
        <businessProcess>Donation</businessProcess>
        <description>Donation Received</description>
        <label>Donation</label>
    </recordTypes>

src/objects/Opportunity_Naming_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings for controlling how Opportunities are named.</description>
    <fields>
        <fullName>Opportunity_Name_Format__c</fullName>
        <description>The format to use for Opportunity naming.</description>
        <inlineHelpText>The format to use for Opportunity naming.</inlineHelpText>
        <label>Opportunity Name Format</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Record_Types__c</fullName>
        <description>Specifies the opportunity record type that this naming scheme is for.</description>
        <inlineHelpText>Specifies the opportunity record type that this naming scheme is for.</inlineHelpText>
        <label>Opportunity Record Types</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Naming Settings</label>
</CustomObject>

src/classes/OPP_OpportunityNaming_TEST.cls
@isTest
private class OPP_OpportunityNaming_TEST
{
    @isTest
    static void itShould()
    {
        Opportunity_Naming_Settings__c ons = new Opportunity_Naming_Settings__c(
            Name = 'foo',
            Opportunity_Record_Types__c = UTIL_RecordTypes.GetRecordTypeId('Opportunity', UTIL_RecordTypes.getrecordTypeNameForGiftsTests('Opportunity')),
            Opportunity_Name_Format__c = '{!Account.Name} {!CloseDate} Donation'
        );
        insert ons;

        Account acc = new Account(Name='foo');
        insert acc;
        Opportunity opp = new Opportunity(
            AccountId = acc.id,
            StageName = UTIL_UnitTestData_TEST.getClosedWonStage(),
            RecordTypeId = UTIL_RecordTypes.GetRecordTypeId('Opportunity', UTIL_RecordTypes.getrecordTypeNameForGiftsTests('Opportunity')),
            Name='temp',
            Amount=8,
            CloseDate = system.today()
        );
        insert opp;

        list<Opportunity> queryOpp = [SELECT Name FROM Opportunity WHERE Id = :opp.id];
        system.assert(queryOpp[0].Name.contains('foo'), 'The name should be calculated based on the setting.');

    }
}