src/objects/Trigger_Handler__c.object
<CustomObject>
    <description>To store which classes to run in response to DML on each object.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates that this module is active</description>
        <inlineHelpText>Indicates that this module is active</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Asynchronous__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that this module should be run asynchronously in this transaction</description>
        <inlineHelpText>Indicates that this module should be run asynchronously in this transaction</inlineHelpText>
        <label>Asynchronous</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <description>Name of the class to be run</description>
        <inlineHelpText>Name of the class to be run</inlineHelpText>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Load_Order__c</fullName>
        <description>Order in which this module should be run, helps maintain dependencies in the modules and data.</description>
        <inlineHelpText>Order in which this module should be run, helps maintain dependencies in the modules and data.</inlineHelpText>
        <label>Load Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Name of the object this module should be run for</description>
        <inlineHelpText>Name of the object this module should be run for</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Actions__c</fullName>
        <description>Trigger Actions in which this module should fire</description>
        <inlineHelpText>Trigger Actions in which this module should fire (beforeinsert, etc.)</inlineHelpText>
        <label>Trigger Actions</label>
        <type>TextArea</type>
    </fields>
    <label>Trigger Handler</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TDTM_ObjectDataGateway.cls
public with sharing class TDTM_ObjectDataGateway implements TDTM_iTableDataGateway {

    private static Map<String, SObject> classesToCallOnTriggers;
    
    public static Map<String, SObject> getClassesToCallOnTriggers() {   
        if (classesToCallOnTriggers == null){
            classesToCallOnTriggers = new Map<String, Trigger_Handler__c>();
            List<Trigger_Handler__c> classesToCallOnTriggersList = [select Asynchronous__c, Class__c, Load_Order__c, Object__c, 
                                                            Active__c, Trigger_Actions__c from Trigger_Handler__c 
                                                            where Active__c = true];
            System.debug('****Number of Trigger_Handler__c records found: ' + classesToCallOnTriggersList.size());
            Integer i = 0; //So that the map keys are different and they don't override each other
            for(Trigger_Handler__c subsys : classesToCallOnTriggersList) {
                classesToCallOnTriggers.put(subsys.Class__c + i, subsys);
                i++;
            }
        }
        System.debug('****Classes to call on triggers: ' + classesToCallOnTriggers.size());
        return classesToCallOnTriggers;
    }
}